modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="AgentSharik"
description='''
Потерянные реликвии древности вновь обрели силу. Fallen Relics возвращает забытый упаковщик, который автоматически обрабатывает рецепты крафта Minecraft и установленных модов. Энергия для его работы не требуется.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="functionalstorage"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="crafttweaker"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"
