modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="AgentSharik"
description='''
A NeoForge 1.21.1 add-on inspired by Auto-Packager. It automatically crafts single-item recipes in 2x2, 3x3, hollow 3x3, and 1x1 modes, with item and energy capabilities for pipe automation.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="functionalstorage"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"
