# -*- coding: utf-8 -*-
# Malum, часть 3в: звуковые подписи.
# Шаблонные подписи блоков (ломка, удар, установка, шаги) и падения генерируются,
# остальные — переведены вручную.

FIXED = {
 '_break': 'Сломан блок',
 '_hit': 'Стук по блоку',
 '_place': 'Блок размещён',
 '_step': 'Шаги',
}

FALL = {
 'malum.subtitle.arcane_charcoal_block_fall': 'Блок арканного древесного угля падает',
 'malum.subtitle.arcane_rock_fall': 'Арканный камень падает',
 'malum.subtitle.arcane_rock_bricks_fall': 'Кирпичи из арканного камня падают',
 'malum.subtitle.blazing_quartz_block_fall': 'Блок пылающего кварца падает',
 'malum.subtitle.blazing_quartz_ore_fall': 'Руда пылающего кварца падает',
 'malum.subtitle.brilliance_block_fall': 'Блок сияния падает',
 'malum.subtitle.brilliance_ore_fall': 'Руда сияния падает',
 'malum.subtitle.deepslate_brilliance_ore_fall': 'Глубиносланцевая руда сияния падает',
 'malum.subtitle.deepslate_quartz_ore_fall': 'Глубиносланцевая кварцевая руда падает',
 'malum.subtitle.deepslate_soulstone_fall': 'Глубиносланцевая руда камня душ падает',
 'malum.subtitle.hallowed_gold_fall': 'Священное золото падает',
 'malum.subtitle.quartz_ore_fall': 'Кварцевая руда падает',
 'malum.subtitle.runewood_fall': 'Рунная древесина падает',
 'malum.subtitle.runewood_hanging_sign_fall': 'Висячая табличка из рунного дерева падает',
 'malum.subtitle.runewood_leaves_fall': 'Листва рунного дерева падает',
 'malum.subtitle.scarstone_fall': 'Камень шрамов падает',
 'malum.subtitle.soul_stained_steel_fall': 'Духосталь падает',
 'malum.subtitle.soulstone_fall': 'Камень душ падает',
 'malum.subtitle.soulwood_fall': 'Древесина души падает',
 'malum.subtitle.soulwood_hanging_sign_fall': 'Висячая табличка из дерева души падает',
 'malum.subtitle.soulwood_leaves_fall': 'Листва дерева души падает',
 'malum.subtitle.spirit_diode_fall': 'Духовный диод падает',
 'malum.subtitle.strange_crystal_fall': 'Странный кристалл падает',
 'malum.subtitle.varnished_terracotta_bricks_fall': 'Кирпичи из глазурованной терракоты падают',
}

P3C = {
 'malum.subtitle.a_soul_shatters': 'Душа раскалывается',
 'malum.subtitle.aesthetica': 'Aesthetica',
 'malum.subtitle.arcane_elegy': 'Arcane Elegy',
 'malum.subtitle.alchemical_trinket_equipped': 'Надет алхимический брелок',
 'malum.subtitle.arcana_codex_closed': 'Кодекс арканы закрыт',
 'malum.subtitle.arcana_codex_opened': 'Кодекс арканы открыт',
 'malum.subtitle.arcana_entry_closed': 'Статья арканы закрыта',
 'malum.subtitle.arcana_entry_hovered': 'Наведение на статью арканы',
 'malum.subtitle.arcana_entry_opened': 'Статья арканы открыта',
 'malum.subtitle.arcana_entry_unhovered': 'Курсор ушёл со статьи арканы',
 'malum.subtitle.arcana_page_flipped': 'Перелистывание страниц арканы',
 'malum.subtitle.arcana_subentry_closed': 'Подраздел арканы закрыт',
 'malum.subtitle.arcana_subentry_opened': 'Подраздел арканы открыт',
 'malum.subtitle.arcana_sweetener_evil': 'Услада арканы (злая)',
 'malum.subtitle.arcana_sweetener_normal': 'Услада арканы (обычная)',
 'malum.subtitle.arcana_transition_evil': 'Переход арканы (злой)',
 'malum.subtitle.arcana_transition_normal': 'Переход арканы (обычный)',
 'malum.subtitle.arcane_whispers': 'Арканный шепот',
 'malum.subtitle.avarice_collected': 'Алчность собрана',
 'malum.subtitle.avarice_grants_fortune': 'Алчность дарует удачу',
 'malum.subtitle.blight_propagates': 'Порча распространяется',
 'malum.subtitle.blight_reacts': 'Порча реагирует',
 'malum.subtitle.blight_reacts_faintly': 'Порча слабо реагирует',
 'malum.subtitle.catalyst_lobber_fired': 'Метатель катализаторов выстрелил',
 'malum.subtitle.catalyst_lobber_locked': 'Метатель катализаторов заблокирован',
 'malum.subtitle.catalyst_lobber_primed': 'Метатель катализаторов взведён',
 'malum.subtitle.catalyst_lobber_unlocked': 'Метатель катализаторов разблокирован',
 'malum.subtitle.cloth_trinket_equipped': 'Надет тканевый брелок',
 'malum.subtitle.completed_ritual_ambience': 'Фон завершённого ритуала',
 'malum.subtitle.concentrated_gluttony_drink': 'Глоток концентрированного чревоугодия',
 'malum.subtitle.crucible_augment_applied': 'Усиление тигля применено',
 'malum.subtitle.crucible_augment_removed': 'Усиление тигля снято',
 'malum.subtitle.echoing_ring_absorbs': 'Кольцо эха поглощает',
 'malum.subtitle.edge_of_deliverance_cuts': 'Грань избавления режет',
 'malum.subtitle.edge_of_deliverance_sweeps': 'Грань избавления размахивает',
 'malum.subtitle.flesh_ring_absorbs': 'Кольцо плоти поглощает',
 'malum.subtitle.gilded_trinket_equipped': 'Надет позолоченный брелок',
 'malum.subtitle.gruesome_ring_feeds': 'Жуткое кольцо насыщается',
 'malum.subtitle.hidden_blade_charged': 'Скрытый клинок заряжен',
 'malum.subtitle.hidden_blade_disrupted': 'Скрытый клинок прерван',
 'malum.subtitle.hidden_blade_primed': 'Скрытый клинок взведён',
 'malum.subtitle.hidden_blade_unleashed': 'Скрытый клинок выпущен',
 'malum.subtitle.hungry_belt_feeds': 'Голодный пояс насыщается',
 'malum.subtitle.impetus_takes_damage': 'Импетус повреждается',
 'malum.subtitle.legalize_nuclear_bombs': 'Легализуйте ядерные бомбы',
 'malum.subtitle.malignant_aegis_charge_completed': 'Заряд злокачественной эгиды завершён',
 'malum.subtitle.malignant_aegis_grows': 'Злокачественная эгида растёт',
 'malum.subtitle.malignant_aegis_nullifies_damage': 'Злокачественная эгида поглощает урон',
 'malum.subtitle.malignant_deliverance_strikes_again': 'Злокачественное избавление бьёт снова',
 'malum.subtitle.malignant_deliverance_triggers': 'Злокачественное избавление срабатывает',
 'malum.subtitle.malignant_disintegrates': 'Злокачественное распадается',
 'malum.subtitle.metallic_trinket_equipped': 'Надет металлический брелок',
 'malum.subtitle.oaken_might_takes_effect': 'Дубовая мощь вступает в силу',
 'malum.subtitle.ornate_trinket_equipped': 'Надет изысканный брелок',
 'malum.subtitle.pedestal_item_inserted': 'Предмет помещён на пьедестал',
 'malum.subtitle.pedestal_item_picked_up': 'Предмет взят с пьедестала',
 'malum.subtitle.pedestal_spirit_inserted': 'Дух помещён на пьедестал',
 'malum.subtitle.pedestal_spirit_picked_up': 'Дух взят с пьедестала',
 'malum.subtitle.player_burns_from_greed': 'Игрок горит от жадности',
 'malum.subtitle.player_experiences_combustion_whiplash': 'Игрока настигает ударная волна взрыва',
 'malum.subtitle.player_patiently_drowns': 'Игрок терпеливо тонет',
 'malum.subtitle.ravenous_pouch_eats': 'Ненасытный мешочек поедает',
 'malum.subtitle.reaper_scythe_slashes': 'Коса жнеца полосует',
 'malum.subtitle.rejected_by_the_unknown': 'Неизвестность отвергает',
 'malum.subtitle.repair_pylon_begins_repairing': 'Пилон починки начинает починку',
 'malum.subtitle.repair_pylon_eagerly_hums': 'Пилон починки нетерпеливо гудит',
 'malum.subtitle.repair_pylon_finishes_repairing': 'Пилон починки завершает починку',
 'malum.subtitle.ritual_absorbs_item': 'Ритуал поглощает предмет',
 'malum.subtitle.ritual_absorbs_spirit': 'Ритуал поглощает дух',
 'malum.subtitle.ritual_beginning_ambience': 'Фон начала ритуала',
 'malum.subtitle.ritual_begins': 'Ритуал начинается',
 'malum.subtitle.ritual_completed': 'Ритуал завершён',
 'malum.subtitle.ritual_evolution_ambience': 'Фон развития ритуала',
 'malum.subtitle.ritual_evolves': 'Ритуал развивается',
 'malum.subtitle.ritual_forms': 'Ритуал формируется',
 'malum.subtitle.rotten_trinket_equipped': 'Надет прогнивший брелок',
 'malum.subtitle.rune_equipped': 'Руна надета',
 'malum.subtitle.runewood_button_click_off': 'Кнопка из рунного дерева отжата',
 'malum.subtitle.runewood_button_click_on': 'Кнопка из рунного дерева нажата',
 'malum.subtitle.runewood_door_close': 'Дверь из рунного дерева закрывается',
 'malum.subtitle.runewood_door_open': 'Дверь из рунного дерева открывается',
 'malum.subtitle.runewood_fence_gate_close': 'Калитка из рунного дерева закрывается',
 'malum.subtitle.runewood_fence_gate_open': 'Калитка из рунного дерева открывается',
 'malum.subtitle.runewood_pressure_plate_click_off': 'Нажимная плита из рунного дерева отжата',
 'malum.subtitle.runewood_pressure_plate_click_on': 'Нажимная плита из рунного дерева нажата',
 'malum.subtitle.runewood_trapdoor_close': 'Люк из рунного дерева закрывается',
 'malum.subtitle.runewood_trapdoor_open': 'Люк из рунного дерева открывается',
 'malum.subtitle.runic_workbench_shapes_something': 'Рунический верстак что-то создаёт',
 'malum.subtitle.runic_workbench_shapes_tainted_rune': 'Рунический верстак создаёт осквернённую руну',
 'malum.subtitle.runic_workbench_shapes_void_rune': 'Рунический верстак создаёт руну пустоты',
 'malum.subtitle.runic_workbench_shapes_wooden_rune': 'Рунический верстак создаёт деревянную руну',
 'malum.subtitle.scarstone_monument_forms': 'Появляется монумент из камня шрамов',
 'malum.subtitle.scythe_caught': 'Коса поймана',
 'malum.subtitle.scythe_cuts': 'Коса режет',
 'malum.subtitle.scythe_spins_happily': 'Коса радостно крутится',
 'malum.subtitle.scythe_sweeps': 'Коса размахивает',
 'malum.subtitle.scythe_target_is_launched': 'Цель косы подброшена',
 'malum.subtitle.scythe_thrown': 'Коса брошена',
 'malum.subtitle.scythe_user_ascends': 'Владелец косы восходит',
 'malum.subtitle.shielding_apparatus_shields': 'Защитное устройство защищает',
 'malum.subtitle.song_of_the_void': 'Песнь пустоты',
 'malum.subtitle.soul_ward_absorbs_damage': 'Оберег души поглощает урон',
 'malum.subtitle.soul_ward_charge_completed': 'Заряд оберега души завершён',
 'malum.subtitle.soul_ward_disintegrates': 'Оберег души распадается',
 'malum.subtitle.soul_ward_grows': 'Оберег души растёт',
 'malum.subtitle.soulbinding_brazier_accepts_offering': 'Жаровня связывания душ принимает подношение',
 'malum.subtitle.soulbinding_brazier_fuses': 'Жаровня связывания душ сплавляет',
 'malum.subtitle.soulbinding_sequence_completed': 'Последовательность связывания завершена',
 'malum.subtitle.soulbinding_sequence_initiated': 'Последовательность связывания начата',
 'malum.subtitle.soulwood_button_click_off': 'Кнопка из дерева души отжата',
 'malum.subtitle.soulwood_button_click_on': 'Кнопка из дерева души нажата',
 'malum.subtitle.soulwood_door_close': 'Дверь из дерева души закрывается',
 'malum.subtitle.soulwood_door_open': 'Дверь из дерева души открывается',
 'malum.subtitle.soulwood_fence_gate_close': 'Калитка из досок дерева души закрывается',
 'malum.subtitle.soulwood_fence_gate_open': 'Калитка из досок дерева души открывается',
 'malum.subtitle.soulwood_pressure_plate_click_off': 'Нажимная плита из дерева души отжата',
 'malum.subtitle.soulwood_pressure_plate_click_on': 'Нажимная плита из дерева души нажата',
 'malum.subtitle.soulwood_trapdoor_close': 'Люк из дерева души закрывается',
 'malum.subtitle.soulwood_trapdoor_open': 'Люк из дерева души открывается',
 'malum.subtitle.spark_bestows_effect': 'Искра дарует эффект',
 'malum.subtitle.spark_bestows_potion_effect': 'Искра дарует эффект зелья',
 'malum.subtitle.spark_directed': 'Искра направлена',
 'malum.subtitle.spark_formed': 'Искра образована',
 'malum.subtitle.spark_unwoven': 'Искра расплетена',
 'malum.subtitle.spell_charge_full': 'Заряд заклинания полон',
 'malum.subtitle.spell_charge_grow': 'Заряд заклинания растёт',
 'malum.subtitle.spellweaving_tool_dampened': 'Инструмент плетения заклинаний ослаблен',
 'malum.subtitle.spellweaving_tool_primed': 'Инструмент плетения заклинаний приведён в готовность',
 'malum.subtitle.spellwoven_sprite_harvests': 'Заклинательный дух собирает урожай',
 'malum.subtitle.spellwoven_sprite_returns': 'Заклинательный дух возвращается',
 'malum.subtitle.spellwoven_sprite_spawns': 'Заклинательный дух появляется',
 'malum.subtitle.spirit_altar_absorbs_item': 'Алтарь духов поглощает предмет',
 'malum.subtitle.spirit_altar_completes_infusion': 'Алтарь духов завершает насыщение',
 'malum.subtitle.spirit_altar_infuses': 'Алтарь духов насыщает',
 'malum.subtitle.spirit_altar_speeds_up': 'Алтарь духов ускоряется',
 'malum.subtitle.spirit_crucible_completes_focusing': 'Тигель духов завершает фокусировку',
 'malum.subtitle.spirit_crucible_focuses': 'Тигель духов фокусируется',
 'malum.subtitle.spirit_diode_close': 'Духовный диод закрывается',
 'malum.subtitle.spirit_diode_open': 'Духовный диод открывается',
 'malum.subtitle.spirit_diode_ticks': 'Духовный диод тикает',
 'malum.subtitle.spirit_diode_ticks_ferociously': 'Духовный диод свирепо тикает',
 'malum.subtitle.spirit_engraved': 'Дух выгравирован',
 'malum.subtitle.spirit_mote_created': 'Создана частица духа',
 'malum.subtitle.spirit_picked_up': 'Дух подобран',
 'malum.subtitle.staff_charged': 'Посох заряжен',
 'malum.subtitle.staff_fires': 'Посох стреляет',
 'malum.subtitle.staff_powers_up': 'Посох набирает силу',
 'malum.subtitle.staff_sizzles_out': 'Посох шипит и гаснет',
 'malum.subtitle.staff_strikes': 'Посох бьёт',
 'malum.subtitle.sundering_anchor_cuts': 'Сокрушающий якорь режет',
 'malum.subtitle.sundering_anchor_lashes_out_ecstatically': 'Сокрушающий якорь исступлённо бьёт',
 'malum.subtitle.sundering_anchor_leaps_out_eagerly': 'Сокрушающий якорь жадно вырывается',
 'malum.subtitle.sundering_anchor_returns_with_euphoria': 'Сокрушающий якорь возвращается с ликованием',
 'malum.subtitle.sundering_anchor_twists_gracefully': 'Сокрушающий якорь изящно извивается',
 'malum.subtitle.suspicious_device_detonates': 'Подозрительное устройство взрывается',
 'malum.subtitle.suspicious_device_detonates_again': 'Подозрительное устройство взрывается снова',
 'malum.subtitle.the_deep_beckons': 'Бездна манит',
 'malum.subtitle.the_heavens_sing': 'Небеса поют',
 'malum.subtitle.the_inverted_heart_shrieks': 'Обращённое сердце визжит',
 'malum.subtitle.the_rot_consumes': 'Гниение пожирает',
 'malum.subtitle.the_rot_spreads': 'Гниение распространяется',
 'malum.subtitle.the_sound_of_silence': 'Звук тишины',
 'malum.subtitle.the_unknown_weeps': 'Неизвестность плачет',
 'malum.subtitle.the_void_heart_beats': 'Сердце пустоты бьётся',
 'malum.subtitle.the_worldsoul_reverberates': 'Душа мира отдаётся эхом',
 'malum.subtitle.the_worldsoul_shifts_erratically': 'Душа мира смещается неровно',
 'malum.subtitle.the_worldsoul_shifts_slightly': 'Душа мира смещается слегка',
 'malum.subtitle.totem_charges': 'Тотем заряжается',
 'malum.subtitle.totem_hums': 'Тотем гудит',
 'malum.subtitle.totemic_growth': 'Тотемный рост',
 'malum.subtitle.totemic_rite_activated': 'Тотемный ритуал активирован',
 'malum.subtitle.totemic_rite_cancelled': 'Тотемный ритуал отменён',
 'malum.subtitle.totemic_rune_equipped': 'Тотемная руна надета',
 'malum.subtitle.totemic_sapping': 'Тотемное истощение',
 'malum.subtitle.totemic_weight': 'Тотемная тяжесть',
 'malum.subtitle.tuning_fork_tinkers': 'Камертон звенит',
 'malum.subtitle.tyrving_slashes_twice': 'Тирвинг полосует дважды',
 'malum.subtitle.void_eats_gunk': 'Пустота поедает слизь',
 'malum.subtitle.void_rune_equipped': 'Руна пустоты надета',
 'malum.subtitle.void_transmutation': 'Трансмутация пустоты',
 'malum.subtitle.void_trinket_equipped': 'Надет брелок пустоты',
 'malum.subtitle.voracious_ring_feeds': 'Ненасытное кольцо насыщается',
 'malum.subtitle.warping_engine_reverberates': 'Двигатель искажения гудит',
 'malum.subtitle.wavebanker_releases': 'Волнонакопитель отдаёт заряд',
 'malum.subtitle.wavebanker_stores': 'Волнонакопитель накапливает заряд',
 'malum.subtitle.wavebreaker_releases': 'Волнопрерыватель отдаёт заряд',
 'malum.subtitle.wavebreaker_stores': 'Волнопрерыватель накапливает заряд',
 'malum.subtitle.wavecharger_charges': 'Волнозарядчик заряжается',
 'malum.subtitle.wavecharger_releases': 'Волнозарядчик отдаёт заряд',
 'malum.subtitle.wavemaker_pulses': 'Волнообразователь пульсирует',
 'malum.subtitle.weavers_workbench_weaves': 'Верстак ткача ткёт',
 'malum.subtitle.weight_of_worlds_cuts': 'Тяжесть миров режет',
 'malum.subtitle.wicked_energy_bursts_forward': 'Скверная энергия рвётся вперёд',
 'malum.subtitle.wrathful_energy_surges': 'Гневная энергия вырывается всплеском',
 'malum.subtitle.wyrd_reconstruction_reconstructs_body': 'Вирд восстановления восстанавливает тело',
}


def build(en):
    """Собирает перевод всех подписей: шаблонные + падения + переведённые вручную."""
    out = {}
    rest = []
    for k in en:
        if not k.startswith('malum.subtitle.'):
            continue
        if k in P3C:
            out[k] = P3C[k]
        elif k in FALL:
            out[k] = FALL[k]
        else:
            hit = False
            for suf, val in FIXED.items():
                if k.endswith(suf) and en[k] in ('Block broken', 'Block breaking', 'Block placed', 'Footsteps'):
                    out[k] = val
                    hit = True
                    break
            if not hit:
                rest.append((k, en[k]))
    return out, rest
