# -*- coding: utf-8 -*-
# Malum, часть 5а: Книга Малума — названия записей, подзаголовки, заголовки страниц
# и информационные блоки (всё, кроме основного текста страниц).
P5A = {
 # ---------- личная записка ----------
 'malum.gui.book.entry.a_personal_note': 'Личная записка',
 'malum.gui.book.entry.a_personal_note.description': 'Страница из другой книги',
 'malum.gui.book.entry.a_personal_note.commendations': 'Malum; Благодарности',
 'malum.gui.book.entry.a_personal_note.commendations.description': 'Письмо с благодарностью',
 'malum.gui.book.entry.a_personal_note.inspirations': 'Malum; Источники вдохновения',
 'malum.gui.book.entry.a_personal_note.inspirations.description': 'То, что привело меня сюда',
 # ---------- записи (названия и подзаголовки) ----------
 'malum.gui.book.entry.accelerating_inlay': 'Ускоряющая вставка',
 'malum.gui.book.entry.accelerating_inlay.description': 'Удвоить ставку',
 'malum.gui.book.entry.aerial_rites': 'Воздушные ритуалы',
 'malum.gui.book.entry.aerial_rites.description': 'Тотемное искусство парения',
 'malum.gui.book.entry.altar_acceleration': 'Ускорение алтаря',
 'malum.gui.book.entry.altar_acceleration.description': 'Обелиски',
 'malum.gui.book.entry.aqueous_rites': 'Водные ритуалы',
 'malum.gui.book.entry.aqueous_rites.description': 'Тотемное искусство течения',
 'malum.gui.book.entry.arcane_restoration': 'Арканное восстановление',
 'malum.gui.book.entry.arcane_restoration.description': 'Мистическая починка',
 'malum.gui.book.entry.arcane_restoration.tool_repair': 'Починка инструментов',
 'malum.gui.book.entry.arcane_restoration.tool_repair.description': 'Починка для духостали',
 'malum.gui.book.entry.aura_empowerment': 'Усиление ауры',
 'malum.gui.book.entry.aura_empowerment.description': 'Улучшенные обелиски',
 'malum.gui.book.entry.aura_empowerment.other_pylon_applications': 'Прочие применения пилона',
 'malum.gui.book.entry.aura_empowerment.other_pylon_applications.description': 'Направление фундаментальных духов',
 'malum.gui.book.entry.authority_of_crushing_melancholy': 'Власть сокрушительной меланхолии',
 'malum.gui.book.entry.authority_of_crushing_melancholy.description': 'Сокрушить собственный дух',
 'malum.gui.book.entry.authority_of_the_gleeful_target': 'Власть радостной мишени',
 'malum.gui.book.entry.authority_of_the_gleeful_target.description': 'Быть самым довольным существом',
 'malum.gui.book.entry.authority_of_the_inverted_heart': 'Власть обращённого сердца',
 'malum.gui.book.entry.authority_of_the_inverted_heart.description': 'Связать все сердца в одно',
 'malum.gui.book.entry.basic_artifice': 'Волновое искусство',
 'malum.gui.book.entry.basic_artifice.description': 'Модуляция сигнала',
 'malum.gui.book.entry.basic_artifice.artificers_claw': 'Коготь искусника',
 'malum.gui.book.entry.basic_artifice.artificers_claw.description': 'Вопреки названию, не острый',
 'malum.gui.book.entry.belt_of_the_magebane': 'Пояс губителя магов',
 'malum.gui.book.entry.belt_of_the_magebane.description': 'Новообретённая гибель',
 'malum.gui.book.entry.belt_of_the_prospector': 'Пояс старателя',
 'malum.gui.book.entry.belt_of_the_prospector.description': 'Сокровища земли',
 'malum.gui.book.entry.belt_of_the_prospector.ring_of_the_demolitionist': 'Кольцо подрывника',
 'malum.gui.book.entry.belt_of_the_prospector.ring_of_the_demolitionist.description': '$bБольше дакки/$',
 'malum.gui.book.entry.belt_of_the_prospector.ring_of_the_hoarder': 'Кольцо собирателя',
 'malum.gui.book.entry.belt_of_the_prospector.ring_of_the_hoarder.description': 'Прямо мне в вены',
 'malum.gui.book.entry.belt_of_the_starved': 'Пояс изголодавшегося',
 'malum.gui.book.entry.belt_of_the_starved.description': 'Направление ненасытности',
 'malum.gui.book.entry.belt_of_the_starved.concentrated_gluttony': 'Концентрированное чревоугодие',
 'malum.gui.book.entry.belt_of_the_starved.concentrated_gluttony.description': 'В обход',
 'malum.gui.book.entry.belt_of_the_starved.ring_of_desperate_voracity': 'Кольцо отчаянной ненасытности',
 'malum.gui.book.entry.belt_of_the_starved.ring_of_desperate_voracity.description': 'Расширяя канал',
 'malum.gui.book.entry.blazing_diode': 'Пылающий диод',
 'malum.gui.book.entry.blazing_diode.description': 'Сильнейшая сила в мире',
 'malum.gui.book.entry.blazing_quartz': 'Пылающий кварц',
 'malum.gui.book.entry.blazing_quartz.description': 'Воспламенение',
 'malum.gui.book.entry.blight': 'Исследование порчи',
 'malum.gui.book.entry.blight.description': 'Что, почему и как',
 'malum.gui.book.entry.brilliance': 'Сияние',
 'malum.gui.book.entry.brilliance.description': 'Материя опыта',
 'malum.gui.book.entry.caustic_catalyst': 'Едкий катализатор',
 'malum.gui.book.entry.caustic_catalyst.description': 'Воспламеняя нестабильность',
 'malum.gui.book.entry.chronicles_of_the_soul': 'Хроники души',
 'malum.gui.book.entry.chronicles_of_the_soul.description': 'Магия чудес',
 'malum.gui.book.entry.chronicles_of_the_void': 'Хроники пустоты',
 'malum.gui.book.entry.chronicles_of_the_void.description': 'Магия безумия',
 'malum.gui.book.entry.crucible_acceleration': 'Ускорение тигля',
 'malum.gui.book.entry.crucible_acceleration.description': 'Разогрев',
 'malum.gui.book.entry.crucible_augmentation': 'Усиление тигля',
 'malum.gui.book.entry.crucible_augmentation.description': 'Настройка настройщика',
 'malum.gui.book.entry.cthonic_gold': 'Хтоническое золото',
 'malum.gui.book.entry.cthonic_gold.description': 'Сплавленное с арканой',
 'malum.gui.book.entry.cthonic_gold.reexamination': 'Переосмысление: хтоническое золото',
 'malum.gui.book.entry.cthonic_gold.reexamination.description': 'Новый принцип в старом материале',
 'malum.gui.book.entry.earthen_rites': 'Земляные ритуалы',
 'malum.gui.book.entry.earthen_rites.description': 'Тотемное искусство формовки',
 'malum.gui.book.entry.elaborate_brooch': 'Затейливая брошь',
 'malum.gui.book.entry.elaborate_brooch.description': 'Смена назначения',
 'malum.gui.book.entry.eldritch_arcana': 'Элдритческая аркана',
 'malum.gui.book.entry.eldritch_arcana.description': 'На всякий толчок найдётся тяга',
 'malum.gui.book.entry.elemental_arcana': 'Стихийная аркана',
 'malum.gui.book.entry.elemental_arcana.description': 'Сфокусированная магия',
 'malum.gui.book.entry.esoteric_reaping': 'Эзотерическая жатва',
 'malum.gui.book.entry.esoteric_reaping.description': 'Просочившаяся магия',
 'malum.gui.book.entry.ether': 'Эфир',
 'malum.gui.book.entry.ether.description': 'Все цвета ветра',
 'malum.gui.book.entry.focus_ashes': 'Восстание пепла',
 'malum.gui.book.entry.focus_ashes.description': 'Создание порошковых реагентов',
 'malum.gui.book.entry.focus_crystals': 'Создание кристаллов',
 'malum.gui.book.entry.focus_crystals.description': 'Формовка кристаллов неправильной формы',
 'malum.gui.book.entry.focus_elemental': 'Воссоздание реликвий',
 'malum.gui.book.entry.focus_elemental.description': 'Создание ядер конструктов',
 'malum.gui.book.entry.focus_metals': 'Магия металлов',
 'malum.gui.book.entry.focus_metals.description': 'Формовка полосчатых кристаллов',
 'malum.gui.book.entry.fragment.void.black_crystal': 'Нацарапанные записи',
 'malum.gui.book.entry.fragment.void.black_crystal.description': 'Непостижимо',
 'malum.gui.book.entry.fragment.void.inverse_and_hybrid_arcana': 'Неудавшийся эксперимент',
 'malum.gui.book.entry.fragment.void.inverse_and_hybrid_arcana.description': 'Попытка создать что-то новое?',
 'malum.gui.book.entry.fragment.void.umbral_arcana': 'Странные уравнения',
 'malum.gui.book.entry.fragment.void.umbral_arcana.description': 'Предполагая отсутствие существования...',
 'malum.gui.book.entry.geas_magic': 'Геасы и прочие клятвы',
 'malum.gui.book.entry.geas_magic.description': 'Сила за цену',
 'malum.gui.book.entry.glass_brooch': 'Стеклянная брошь',
 'malum.gui.book.entry.glass_brooch.description': 'Хрупкая сила',
 'malum.gui.book.entry.gluttonous_brooch': 'Прожорливая брошь',
 'malum.gui.book.entry.gluttonous_brooch.description': 'Бесконечно ненасытная',
 'malum.gui.book.entry.impurity_stabilizer': 'Стабилизатор примесей',
 'malum.gui.book.entry.impurity_stabilizer.description': 'Мощь из слабости',
 'malum.gui.book.entry.infernal_rites': 'Инфернальные ритуалы',
 'malum.gui.book.entry.infernal_rites.description': 'Тотемное искусство опаления',
 'malum.gui.book.entry.intricate_assembly': 'Замысловатая сборка',
 'malum.gui.book.entry.intricate_assembly.description': 'Подгонка чисел',
 'malum.gui.book.entry.introduction': 'Введение',
 'malum.gui.book.entry.introduction.description': 'О природе душ',
 'malum.gui.book.entry.locus_management': 'Управление очагом',
 'malum.gui.book.entry.locus_management.description': 'Аркана в движении',
 'malum.gui.book.entry.managing_totems': 'Резонанс тотема',
 'malum.gui.book.entry.managing_totems.description': 'Взгляд на ритуалы',
 'malum.gui.book.entry.mending_diffuser': 'Диффузор починки',
 'malum.gui.book.entry.mending_diffuser.description': 'Неживая рубцовая ткань',
 'malum.gui.book.entry.mirror_magic': 'Магия зеркал',
 'malum.gui.book.entry.mirror_magic.description': 'Магические воронки',
 'malum.gui.book.entry.mote_making': 'Создание частиц',
 'malum.gui.book.entry.mote_making.description': 'Поклоняйся кубу',
 'malum.gui.book.entry.natural_quartz': 'Природный кварц',
 'malum.gui.book.entry.natural_quartz.description': 'В глубинах земли',
 'malum.gui.book.entry.necklace_of_blissful_harmony': 'Ожерелье блаженной гармонии',
 'malum.gui.book.entry.necklace_of_blissful_harmony.description': 'Не видно, чтобы занималось утро',
 'malum.gui.book.entry.necklace_of_the_mystic_mirror': 'Ожерелье мистического зеркала',
 'malum.gui.book.entry.necklace_of_the_mystic_mirror.description': 'Как снаружи, так и внутри',
 'malum.gui.book.entry.necklace_of_the_narrow_edge': 'Ожерелье узкой грани',
 'malum.gui.book.entry.necklace_of_the_narrow_edge.description': 'Сфокусировано и заточено',
 'malum.gui.book.entry.necklace_of_the_narrow_edge.ring_of_the_howling_maelstrom': 'Кольцо воющего водоворота',
 'malum.gui.book.entry.necklace_of_the_narrow_edge.ring_of_the_howling_maelstrom.description': '30 % шанс увернуться',
 'malum.gui.book.entry.necklace_of_the_narrow_edge.ring_of_the_rising_edge': 'Кольцо восходящей грани',
 'malum.gui.book.entry.necklace_of_the_narrow_edge.ring_of_the_rising_edge.description': 'Нажатие есть нажатие',
 'malum.gui.book.entry.oath_of_the_overburdened_mind': 'Клятва обременённого разума',
 'malum.gui.book.entry.oath_of_the_overburdened_mind.description': 'Бить сокрушительно',
 'malum.gui.book.entry.oath_of_the_overeager_fist': 'Клятва слишком рьяного кулака',
 'malum.gui.book.entry.oath_of_the_overeager_fist.description': 'Никогда не медлить',
 'malum.gui.book.entry.oath_of_the_overkeen_eye': 'Клятва слишком зоркого глаза',
 'malum.gui.book.entry.oath_of_the_overkeen_eye.description': 'Попадать в цель',
 'malum.gui.book.entry.oath_of_the_undiscerned_maw': 'Клятва неразличимой утробы',
 'malum.gui.book.entry.oath_of_the_undiscerned_maw.description': 'Пожрать всё',
 'malum.gui.book.entry.oath_of_unmakers_disdain': 'Клятва презрения разрушителя',
 'malum.gui.book.entry.oath_of_unmakers_disdain.description': 'Властвовать свысока',
 'malum.gui.book.entry.oath_of_unsighted_resistance': 'Клятва незрячего сопротивления',
 'malum.gui.book.entry.oath_of_unsighted_resistance.description': 'Брести сквозь бойню',
 'malum.gui.book.entry.pact_of_combustion': 'Пакт горения',
 'malum.gui.book.entry.pact_of_combustion.description': 'Питать пламя',
 'malum.gui.book.entry.pact_of_contentedness': 'Пакт довольства',
 'malum.gui.book.entry.pact_of_contentedness.description': 'Искать довольства',
 'malum.gui.book.entry.pact_of_defiance': 'Пакт непокорности',
 'malum.gui.book.entry.pact_of_defiance.description': 'Не признавать предела',
 'malum.gui.book.entry.pact_of_patience_repaid': 'Пакт возданного терпения',
 'malum.gui.book.entry.pact_of_patience_repaid.description': 'Разбавить свою боль',
 'malum.gui.book.entry.pact_of_reciprocation': 'Пакт взаимности',
 'malum.gui.book.entry.pact_of_reciprocation.description': 'Два глаза за глаз',
 'malum.gui.book.entry.pact_of_rune_exploitation': 'Пакт использования рун',
 'malum.gui.book.entry.pact_of_rune_exploitation.description': 'Следовать древним пактам',
 'malum.gui.book.entry.pact_of_self_care': 'Пакт заботы о себе',
 'malum.gui.book.entry.pact_of_self_care.description': 'Заботиться о себе',
 'malum.gui.book.entry.pact_of_the_arcanaphage': 'Пакт арканофага',
 'malum.gui.book.entry.pact_of_the_arcanaphage.description': 'Выйти за пределы себя',
 'malum.gui.book.entry.pact_of_the_berserker': 'Пакт берсерка',
 'malum.gui.book.entry.pact_of_the_berserker.description': 'Отплатить болью за боль',
 'malum.gui.book.entry.pact_of_the_blastweaver': 'Пакт ткача взрывов',
 'malum.gui.book.entry.pact_of_the_blastweaver.description': 'Пожинать с руин',
 'malum.gui.book.entry.pact_of_the_cloudskipper': 'Пакт скачущего по облакам',
 'malum.gui.book.entry.pact_of_the_cloudskipper.description': 'Взойти превыше всех',
 'malum.gui.book.entry.pact_of_the_continuing_shot': 'Пакт непрерывного выстрела',
 'malum.gui.book.entry.pact_of_the_continuing_shot.description': 'Стать стрелой',
 'malum.gui.book.entry.pact_of_the_fortress': 'Пакт крепости',
 'malum.gui.book.entry.pact_of_the_fortress.description': 'Стоять и оборонять',
 'malum.gui.book.entry.pact_of_the_high_priest': 'Пакт верховного жреца',
 'malum.gui.book.entry.pact_of_the_high_priest.description': 'Распылять себя',
 'malum.gui.book.entry.pact_of_the_lifeweaver': 'Пакт ткача жизни',
 'malum.gui.book.entry.pact_of_the_lifeweaver.description': 'Делиться со всеми без разбора',
 'malum.gui.book.entry.pact_of_the_lone_druid': 'Пакт одинокого друида',
 'malum.gui.book.entry.pact_of_the_lone_druid.description': 'Чураться сделанного руками',
 'malum.gui.book.entry.pact_of_the_parasite': 'Пакт паразита',
 'malum.gui.book.entry.pact_of_the_parasite.description': 'Прятаться за чужими щитами',
 'malum.gui.book.entry.pact_of_the_profane_ascetic': 'Пакт нечестивого аскета',
 'malum.gui.book.entry.pact_of_the_profane_ascetic.description': 'Искать красоту в отбросах',
 'malum.gui.book.entry.pact_of_the_profane_glutton': 'Пакт нечестивого чревоугодника',
 'malum.gui.book.entry.pact_of_the_profane_glutton.description': 'Поглощать',
 'malum.gui.book.entry.pact_of_the_prospector': 'Пакт старателя',
 'malum.gui.book.entry.pact_of_the_prospector.description': 'Приумножать своё богатство',
 'malum.gui.book.entry.pact_of_the_reaper': 'Пакт жнеца',
 'malum.gui.book.entry.pact_of_the_reaper.description': 'Овладеть жатвенным лезвием',
 'malum.gui.book.entry.pact_of_the_shattering_addict': 'Пакт зависимости от раскалывания',
 'malum.gui.book.entry.pact_of_the_shattering_addict.description': 'Раскалывать и раскалывать',
 'malum.gui.book.entry.pact_of_the_shield': 'Пакт щита',
 'malum.gui.book.entry.pact_of_the_shield.description': 'Всегда ходить настороже',
 'malum.gui.book.entry.pact_of_the_skybreaker': 'Пакт разящего небеса',
 'malum.gui.book.entry.pact_of_the_skybreaker.description': 'Обрушить всё вниз',
 'malum.gui.book.entry.pact_of_the_warlock': 'Пакт колдуна',
 'malum.gui.book.entry.pact_of_the_warlock.description': 'Сражаться вечно',
 'malum.gui.book.entry.pact_of_the_windswept': 'Пакт овеянного ветром',
 'malum.gui.book.entry.pact_of_the_windswept.description': 'Стать единым с ветром',
 'malum.gui.book.entry.pact_of_tidal_affinity': 'Пакт приливного родства',
 'malum.gui.book.entry.pact_of_tidal_affinity.description': 'Стать единым с морем',
 'malum.gui.book.entry.pact_of_wyrd_reconstruction': 'Пакт восстановления вирдом',
 'malum.gui.book.entry.pact_of_wyrd_reconstruction.description': 'Пережить свою судьбу',
 'malum.gui.book.entry.pacts_of_an_igneous_shaper': 'Пакты магматического ваятеля',
 'malum.gui.book.entry.pacts_of_an_igneous_shaper.description': 'Связать первозданную мантию',
 'malum.gui.book.entry.pacts_of_an_inward_soul': 'Пакты обращённой внутрь души',
 'malum.gui.book.entry.pacts_of_an_inward_soul.description': 'Перекроить фундаментальные аспекты',
 'malum.gui.book.entry.pacts_of_an_unbound_wayfarer': 'Пакт свободного странника',
 'malum.gui.book.entry.pacts_of_an_unbound_wayfarer.description': 'Парить сквозь бури и приливы',
 'malum.gui.book.entry.pacts_of_an_uneven_conscience': 'Пакт неровной совести',
 'malum.gui.book.entry.pacts_of_an_uneven_conscience.description': 'Требовать ясности в хаотичном мире',
 'malum.gui.book.entry.primary_arcana': 'Первичная аркана',
 'malum.gui.book.entry.primary_arcana.description': 'Составляющие магии',
 'malum.gui.book.entry.prismatic_focus_lens': 'Призматическая фокусная линза',
 'malum.gui.book.entry.prismatic_focus_lens.description': 'Стабильность',
 'malum.gui.book.entry.reactive_trinkets': 'Отзывчивые аксессуары',
 'malum.gui.book.entry.reactive_trinkets.description': 'Упряжь жатвы',
 'malum.gui.book.entry.resonance_tuner': 'Настройщик резонанса',
 'malum.gui.book.entry.resonance_tuner.description': 'Гашение диссонанса',
 'malum.gui.book.entry.ring_of_esoteric_spoils': 'Кольцо эзотерических трофеев',
 'malum.gui.book.entry.ring_of_esoteric_spoils.description': 'Плодитесь и размножайтесь',
 'malum.gui.book.entry.rite_of_ascension': 'Ритуал восхождения',
 'malum.gui.book.entry.rite_of_ascension.description': 'Обратить закон вспять',
 'malum.gui.book.entry.rite_of_creation': 'Ритуал созидания',
 'malum.gui.book.entry.rite_of_creation.description': 'Создать из ничего',
 'malum.gui.book.entry.rite_of_culling': 'Ритуал выбраковки',
 'malum.gui.book.entry.rite_of_culling.description': 'Проредить стадо',
 'malum.gui.book.entry.rite_of_destruction': 'Ритуал разрушения',
 'malum.gui.book.entry.rite_of_destruction.description': 'Уничтожить сотворённое',
 'malum.gui.book.entry.rite_of_empowerment': 'Ритуал усиления',
 'malum.gui.book.entry.rite_of_empowerment.description': 'Выковать силу',
 'malum.gui.book.entry.rite_of_gravity': 'Ритуал гравитации',
 'malum.gui.book.entry.rite_of_gravity.description': 'Наделить тяжестью',
 'malum.gui.book.entry.rite_of_harming': 'Ритуал вреда',
 'malum.gui.book.entry.rite_of_harming.description': 'Ранить глубоко',
 'malum.gui.book.entry.rite_of_healing': 'Ритуал исцеления',
 'malum.gui.book.entry.rite_of_healing.description': 'Залечить открытые раны',
 'malum.gui.book.entry.rite_of_lust': 'Ритуал похоти',
 'malum.gui.book.entry.rite_of_lust.description': 'Пробудить желания',
 'malum.gui.book.entry.rite_of_nourishment': 'Ритуал насыщения',
 'malum.gui.book.entry.rite_of_nourishment.description': 'Напитать тело',
 'malum.gui.book.entry.rite_of_nurturing': 'Ритуал взращивания',
 'malum.gui.book.entry.rite_of_nurturing.description': 'Взрастить молодую жизнь',
 'malum.gui.book.entry.rite_of_quickening': 'Ритуал ускорения',
 'malum.gui.book.entry.rite_of_quickening.description': 'Ускорить процесс',
 'malum.gui.book.entry.rite_of_rending': 'Ритуал растерзания',
 'malum.gui.book.entry.rite_of_rending.description': 'Запечатать свою судьбу',
 'malum.gui.book.entry.rite_of_sapping': 'Ритуал источения',
 'malum.gui.book.entry.rite_of_sapping.description': 'Собирать с земли',
 'malum.gui.book.entry.rite_of_smelting': 'Ритуал плавки',
 'malum.gui.book.entry.rite_of_smelting.description': 'Очистить сырое',
 'malum.gui.book.entry.rite_of_soaking': 'Ритуал орошения',
 'malum.gui.book.entry.rite_of_soaking.description': 'Дать природе расти',
 'malum.gui.book.entry.rite_of_the_burning_fervor': 'Ритуал пылающего рвения',
 'malum.gui.book.entry.rite_of_the_burning_fervor.description': 'Воспламенить свой дух',
 'malum.gui.book.entry.rite_of_the_fiery_embrace': 'Ритуал огненных объятий',
 'malum.gui.book.entry.rite_of_the_fiery_embrace.description': 'Усмирить своё пламя',
 'malum.gui.book.entry.rite_of_the_flowing_grasp': 'Ритуал текучей хватки',
 'malum.gui.book.entry.rite_of_the_flowing_grasp.description': 'Продлить свою хватку',
 'malum.gui.book.entry.rite_of_the_good_tides': 'Ритуал благоприятных приливов',
 'malum.gui.book.entry.rite_of_the_good_tides.description': 'Благословить свои дары',
 'malum.gui.book.entry.rite_of_the_howling_gale': 'Ритуал воющего шквала',
 'malum.gui.book.entry.rite_of_the_howling_gale.description': 'Ускорить свой дух',
 'malum.gui.book.entry.rite_of_the_oaken_might': 'Ритуал дубовой мощи',
 'malum.gui.book.entry.rite_of_the_oaken_might.description': 'Окостенить свои удары',
 'malum.gui.book.entry.rite_of_the_sky_tether': 'Ритуал небесного поводка',
 'malum.gui.book.entry.rite_of_the_sky_tether.description': 'Поднять свою тяжесть',
 'malum.gui.book.entry.rite_of_the_stone_ward': 'Ритуал каменной защиты',
 'malum.gui.book.entry.rite_of_the_stone_ward.description': 'Закалить свою плоть',
 'malum.gui.book.entry.ritual_magic': 'Ритуальная магия',
 'malum.gui.book.entry.ritual_magic.description': 'Великие магии',
 'malum.gui.book.entry.rune_of_ailment_cleansing': 'Руна очищения от недугов',
 'malum.gui.book.entry.rune_of_ailment_cleansing.description': 'Порыв к переработке',
 'malum.gui.book.entry.rune_of_burning_fervor': 'Руна пылающего рвения',
 'malum.gui.book.entry.rune_of_burning_fervor.description': 'Заостряя ваши порывы',
 'malum.gui.book.entry.rune_of_culling': 'Руна добивания',
 'malum.gui.book.entry.rune_of_culling.description': 'Порыв ломать',
 'malum.gui.book.entry.rune_of_dexterity': 'Руна ловкости',
 'malum.gui.book.entry.rune_of_dexterity.description': 'Порыв бежать',
 'malum.gui.book.entry.rune_of_fiery_embrace': 'Руна огненных объятий',
 'malum.gui.book.entry.rune_of_fiery_embrace.description': 'Угашая ваши порывы',
 'malum.gui.book.entry.rune_of_flowing_grasp': 'Руна текучей хватки',
 'malum.gui.book.entry.rune_of_flowing_grasp.description': 'Заземляя ваши порывы',
 'malum.gui.book.entry.rune_of_good_tides': 'Руна благоприятных приливов',
 'malum.gui.book.entry.rune_of_good_tides.description': 'Благословляя ваши порывы',
 'malum.gui.book.entry.rune_of_howling_gale': 'Руна воющего шквала',
 'malum.gui.book.entry.rune_of_howling_gale.description': 'Ускоряя ваши порывы',
 'malum.gui.book.entry.rune_of_oaken_might': 'Руна дубовой мощи',
 'malum.gui.book.entry.rune_of_oaken_might.description': 'Усиливая ваши порывы',
 'malum.gui.book.entry.rune_of_protection': 'Руна защиты',
 'malum.gui.book.entry.rune_of_protection.description': 'Порыв выстоять',
 'malum.gui.book.entry.rune_of_reinforcement': 'Руна подкрепления',
 'malum.gui.book.entry.rune_of_reinforcement.description': 'Порыв созидать',
 'malum.gui.book.entry.rune_of_scorching': 'Руна опаления',
 'malum.gui.book.entry.rune_of_scorching.description': 'Порыв жечь',
 'malum.gui.book.entry.rune_of_sky_tether': 'Руна небесного поводка',
 'malum.gui.book.entry.rune_of_sky_tether.description': 'Возвышая ваши порывы',
 'malum.gui.book.entry.rune_of_stone_ward': 'Руна каменной защиты',
 'malum.gui.book.entry.rune_of_stone_ward.description': 'Оберегая ваши порывы',
 'malum.gui.book.entry.rune_of_vitality': 'Руна живучести',
 'malum.gui.book.entry.rune_of_vitality.description': 'Порыв исцелять',
 'malum.gui.book.entry.rune_of_volatile_distortion': 'Руна нестабильного искажения',
 'malum.gui.book.entry.rune_of_volatile_distortion.description': 'Порыв разлагать',
 'malum.gui.book.entry.runewood': 'Рунное дерево',
 'malum.gui.book.entry.runewood.description': 'Арканный дуб',
 'malum.gui.book.entry.runeworking': 'Создание рун',
 'malum.gui.book.entry.runeworking.description': 'Центральный стержень',
 'malum.gui.book.entry.runic_brooch': 'Руническая брошь',
 'malum.gui.book.entry.runic_brooch.description': 'Сила в ладонях',
 'malum.gui.book.entry.sacred_rites': 'Сакральные ритуалы',
 'malum.gui.book.entry.sacred_rites.description': 'Тотемное искусство исцеления',
 'malum.gui.book.entry.scarstone': 'Исследование камня шрамов',
 'malum.gui.book.entry.scarstone.description': 'Искажённая порода',
 'malum.gui.book.entry.scythes': 'Косы',
 'malum.gui.book.entry.scythes.description': 'Жатва',
 'malum.gui.book.entry.scythes.enchanting': 'Зачарование косы',
 'malum.gui.book.entry.scythes.enchanting.description': 'Два способа содрать шкуру с души',
 'malum.gui.book.entry.shielding_apparatus': 'Защитное устройство',
 'malum.gui.book.entry.shielding_apparatus.description': 'Оплот против бури',
 'malum.gui.book.entry.soulhunter_armor': 'Броня охотника за душами',
 'malum.gui.book.entry.soulhunter_armor.description': 'Словно из стекла',
 'malum.gui.book.entry.soulstained_armor': 'Броня из духостали',
 'malum.gui.book.entry.soulstained_armor.description': 'Духовная защита',
 'malum.gui.book.entry.soulstained_scythe': 'Коса из духостали',
 'malum.gui.book.entry.soulstained_scythe.description': 'Жни',
 'malum.gui.book.entry.soulstone': 'Камень душ',
 'malum.gui.book.entry.soulstone.description': 'Вне фазы',
 'malum.gui.book.entry.soulwood': 'Исследование дерева душ',
 'malum.gui.book.entry.soulwood.description': 'Искажённые деревья',
 'malum.gui.book.entry.soulwoven_pouch': 'Мешочек, сотканный из душ',
 'malum.gui.book.entry.soulwoven_pouch.description': 'Шаг, прыжок и рука наружу',
 'malum.gui.book.entry.soulwoven_pouch.ravenous_pouch': 'Ненасытный мешочек',
 'malum.gui.book.entry.soulwoven_pouch.ravenous_pouch.description': 'А теперь сделайте его голодным.',
 'malum.gui.book.entry.soulwoven_silk': 'Шёлк, сотканный из душ',
 'malum.gui.book.entry.soulwoven_silk.description': 'Ткать мимолётное',
 'malum.gui.book.entry.spellweaving_axe': 'Топор плетения заклинаний',
 'malum.gui.book.entry.spellweaving_axe.description': 'Жать у природы',
 'malum.gui.book.entry.spellweaving_pickaxe': 'Кирка плетения заклинаний',
 'malum.gui.book.entry.spellweaving_pickaxe.description': 'Жать у камня',
 'malum.gui.book.entry.spellweaving_tools.enchanting': 'Зачарование сотканного',
 'malum.gui.book.entry.spellweaving_tools.enchanting.description': 'Усиление очагов',
 'malum.gui.book.entry.spirit_crystals': 'Кристаллы духов',
 'malum.gui.book.entry.spirit_crystals.description': 'Материя и магия',
 'malum.gui.book.entry.spirit_focusing': 'Фокусировка духов',
 'malum.gui.book.entry.spirit_focusing.description': 'Мистическое размножение',
 'malum.gui.book.entry.spirit_infusion': 'Насыщение духами',
 'malum.gui.book.entry.spirit_infusion.description': 'Сотворение чудес',
 'malum.gui.book.entry.spirit_infusion.alchemical_calx': 'Алхимическая окалина',
 'malum.gui.book.entry.spirit_infusion.alchemical_calx.description': 'Глина 2',
 'malum.gui.book.entry.spirit_infusion.hex_ash': 'Колдовской пепел',
 'malum.gui.book.entry.spirit_infusion.hex_ash.description': 'Обязательный магический порошок',
 'malum.gui.book.entry.spirit_infusion.living_flesh': 'Живая плоть',
 'malum.gui.book.entry.spirit_infusion.living_flesh.description': 'Пожалуйста, не пытайтесь это съесть',
 'malum.gui.book.entry.spirit_jar': 'Хранилище духов',
 'malum.gui.book.entry.spirit_jar.description': 'Арканные архивы',
 'malum.gui.book.entry.spirit_metals.hallowed_gold': 'Священное золото',
 'malum.gui.book.entry.spirit_metals.hallowed_gold.description': 'Привести в лад',
 'malum.gui.book.entry.spirit_metals.reexamination': 'Переосмысление: металлы духов',
 'malum.gui.book.entry.spirit_metals.reexamination.description': 'Иной принцип',
 'malum.gui.book.entry.spirit_metals.soul_stained_steel': 'Духосталь',
 'malum.gui.book.entry.spirit_metals.soul_stained_steel.description': 'Сплавить реальности',
 'malum.gui.book.entry.spirit_minerals.reexamination': 'Переосмысление: камень душ и сияние',
 'malum.gui.book.entry.spirit_minerals.reexamination.description': 'Больше, чем просто аркана',
 'malum.gui.book.entry.spirit_stones': 'Камни духов',
 'malum.gui.book.entry.spirit_stones.description': 'Пропитать арканой',
 'malum.gui.book.entry.spirit_stones.reexamination': 'Переосмысление: камни духов',
 'malum.gui.book.entry.spirit_stones.reexamination.description': 'Мозаика кристаллических структур',
 'malum.gui.book.entry.spirit_trinkets': 'Аксессуары духов',
 'malum.gui.book.entry.spirit_trinkets.description': 'Подбор украшений',
 'malum.gui.book.entry.spirited_glass': 'Стекло духов',
 'malum.gui.book.entry.spirited_glass.description': 'Не подходит для окуляторов',
 'malum.gui.book.entry.strange_crystal.reexamination': 'Переосмысление: странный кристалл',
 'malum.gui.book.entry.strange_crystal.reexamination.description': 'Поразительное сходство',
 'malum.gui.book.entry.strange_crystal.revelation': 'Откровение: странный кристалл',
 'malum.gui.book.entry.strange_crystal.revelation.description': 'Странного рода жизнь',
 'malum.gui.book.entry.suspicious_device': 'Подозрительное устройство',
 'malum.gui.book.entry.suspicious_device.description': 'Поучительная история',
 'malum.gui.book.entry.sympathy_drive': 'Привод симпатии',
 'malum.gui.book.entry.sympathy_drive.description': 'Укрощение ненависти',
 'malum.gui.book.entry.the_device': 'Устройство.',
 'malum.gui.book.entry.the_device.description': 'микроволновка для подзарядки',
 'malum.gui.book.entry.totem_magic': 'Магия тотемов',
 'malum.gui.book.entry.totem_magic.description': 'Чудеса в мире',
 'malum.gui.book.entry.totem_magic.waveform_totemancy': 'Волновая тотемантия',
 'malum.gui.book.entry.totem_magic.waveform_totemancy.description': 'Ритуал и лево',
 'malum.gui.book.entry.tyrving': 'Тирвинг',
 'malum.gui.book.entry.tyrving.description': 'Древняя реликвия',
 'malum.gui.book.entry.unchained_rite': 'Освобождённый ритуал',
 'malum.gui.book.entry.unchained_rite.description': 'Созидание без контроля',
 'malum.gui.book.entry.unchained_transmutation': 'Освобождённая трансмутация',
 'malum.gui.book.entry.unchained_transmutation.description': 'Нестабильные реакции',
 'malum.gui.book.entry.undirected_rite': 'Ненаправленный ритуал',
 'malum.gui.book.entry.undirected_rite.description': 'Созидание без направления',
 'malum.gui.book.entry.undoing_geas_bindings': 'Отречение от геасов',
 'malum.gui.book.entry.undoing_geas_bindings.description': 'За слишком высокую цену',
 'malum.gui.book.entry.varnished_terracotta': 'Глазурованная терракота',
 'malum.gui.book.entry.varnished_terracotta.description': 'Славные узоры',
 'malum.gui.book.entry.void.belt_of_the_limitless': 'Пояс безграничности',
 'malum.gui.book.entry.void.belt_of_the_limitless.description': 'Непостижимая любовь',
 'malum.gui.book.entry.void.black_crystal': 'Чёрный кристалл',
 'malum.gui.book.entry.void.black_crystal.description': 'Ошибка или дар?',
 'malum.gui.book.entry.void.catalyst_lobber': 'Метатель катализаторов',
 'malum.gui.book.entry.void.catalyst_lobber.description': 'Прогресс обгоняет',
 'malum.gui.book.entry.void.edge_of_deliverance': 'Грань избавления',
 'malum.gui.book.entry.void.edge_of_deliverance.description': 'Мелодия безумного крикуна',
 'malum.gui.book.entry.void.erosion_scepter': 'Скипетр эрозии',
 'malum.gui.book.entry.void.erosion_scepter.description': 'Да убоятся маги моей мощи',
 'malum.gui.book.entry.void.fused_consciousness': 'Слитое сознание',
 'malum.gui.book.entry.void.fused_consciousness.description': 'Чертёж всего, что было и будет',
 'malum.gui.book.entry.void.inverse_and_hybrid_arcana': 'Обратная и гибридная аркана?',
 'malum.gui.book.entry.void.inverse_and_hybrid_arcana.description': 'Несостоявшиеся теории',
 'malum.gui.book.entry.void.malignant_pewter': 'Злокачественный пьютер',
 'malum.gui.book.entry.void.malignant_pewter.description': 'Прогресс, отлитый во лжи',
 'malum.gui.book.entry.void.malignant_stronghold_armor': 'Броня злокачественной твердыни',
 'malum.gui.book.entry.void.malignant_stronghold_armor.description': 'Защита неизбежного',
 'malum.gui.book.entry.void.material_study_arcana': 'Исследование материала: аркана',
 'malum.gui.book.entry.void.material_study_arcana.description': 'Новая глубина старых колодцев',
 'malum.gui.book.entry.void.material_study_auric_embers': 'Исследование материала: пылающее возвышение',
 'malum.gui.book.entry.void.material_study_auric_embers.description': 'Суть прогресса',
 'malum.gui.book.entry.void.material_study_auric_embers.reexamination': 'Переосмысление: золотистый уголь',
 'malum.gui.book.entry.void.material_study_auric_embers.reexamination.description': 'Не отсекая, а обращая',
 'malum.gui.book.entry.void.material_study_malignant_lead': 'Исследование материала: прогнившее золото',
 'malum.gui.book.entry.void.material_study_malignant_lead.description': 'Совершенство, отлитое в низкое',
 'malum.gui.book.entry.void.material_study_malignant_lead.reexamination': 'Переосмысление: злокачественный свинец',
 'malum.gui.book.entry.void.material_study_malignant_lead.reexamination.description': 'Скверный и теневой',
 'malum.gui.book.entry.void.material_study_mnemonic_fragment': 'Исследование материала: сгущённое сияние',
 'malum.gui.book.entry.void.material_study_mnemonic_fragment.description': 'Не опыт, а память',
 'malum.gui.book.entry.void.material_study_mnemonic_fragment.reexamination': 'Переосмысление: Мнемозина',
 'malum.gui.book.entry.void.material_study_mnemonic_fragment.reexamination.description': 'Закономерности остаются верны',
 'malum.gui.book.entry.void.material_study_null_slate': 'Исследование материала: очищенный камень душ',
 'malum.gui.book.entry.void.material_study_null_slate.description': 'Чистая скрижаль, возможно, предшественник',
 'malum.gui.book.entry.void.material_study_null_slate.reexamination': 'Переосмысление: пустая скрижаль',
 'malum.gui.book.entry.void.material_study_null_slate.reexamination.description': 'Настроена на теневое',
 'malum.gui.book.entry.void.material_study_soulstone': 'Исследование материала: камень душ',
 'malum.gui.book.entry.void.material_study_soulstone.description': 'Старый друг',
 'malum.gui.book.entry.void.material_study_void_salts': 'Исследование материала: очищенный пепел',
 'malum.gui.book.entry.void.material_study_void_salts.description': 'Ключ к природе душ',
 'malum.gui.book.entry.void.material_study_void_salts.reexamination': 'Переосмысление: пустотная соль',
 'malum.gui.book.entry.void.material_study_void_salts.reexamination.description': 'Тревожно',
 'malum.gui.book.entry.void.necklace_of_the_hidden_blade': 'Ожерелье скрытого клинка',
 'malum.gui.book.entry.void.necklace_of_the_hidden_blade.description': 'Нож в спину им',
 'malum.gui.book.entry.void.necklace_of_the_watcher': 'Ожерелье наблюдателя',
 'malum.gui.book.entry.void.necklace_of_the_watcher.description': 'Оно смотрит в ответ',
 'malum.gui.book.entry.void.ring_of_echoing_arcana': 'Кольцо эха арканы',
 'malum.gui.book.entry.void.ring_of_echoing_arcana.description': 'Я вижу-вижу будущее $iбудущее/$',
 'malum.gui.book.entry.void.ring_of_growing_flesh': 'Кольцо растущей плоти',
 'malum.gui.book.entry.void.ring_of_growing_flesh.description': 'Ползёт и копошится',
 'malum.gui.book.entry.void.ring_of_gruesome_concentration': 'Кольцо жуткой концентрации',
 'malum.gui.book.entry.void.ring_of_gruesome_concentration.description': 'Поглоти и включи в себя',
 'malum.gui.book.entry.void.rune_of_bolstering': 'Руна укрепления',
 'malum.gui.book.entry.void.rune_of_bolstering.description': 'Исцелить то, что цело',
 'malum.gui.book.entry.void.rune_of_heresy': 'Руна ереси',
 'malum.gui.book.entry.void.rune_of_heresy.description': 'Разрушить то, что создаёт',
 'malum.gui.book.entry.void.rune_of_igneous_solace': 'Руна огненного утешения',
 'malum.gui.book.entry.void.rune_of_igneous_solace.description': 'Питать то, что должно гореть',
 'malum.gui.book.entry.void.rune_of_indomitability': 'Руна неукротимости',
 'malum.gui.book.entry.void.rune_of_indomitability.description': 'Вынести то, что должно сломаться',
 'malum.gui.book.entry.void.rune_of_radial_empowerment': 'Руна жертвенного усиления',
 'malum.gui.book.entry.void.rune_of_radial_empowerment.description': 'Сломать то, что сломано',
 'malum.gui.book.entry.void.rune_of_spell_mastery': 'Руна мастерства заклинаний',
 'malum.gui.book.entry.void.rune_of_spell_mastery.description': 'Создать то, что разрушает',
 'malum.gui.book.entry.void.rune_of_twinned_duration': 'Руна двойной длительности',
 'malum.gui.book.entry.void.rune_of_twinned_duration.description': 'Приостановить то, что должно перерабатываться',
 'malum.gui.book.entry.void.rune_of_unnatural_stamina': 'Руна противоестественной выносливости',
 'malum.gui.book.entry.void.rune_of_unnatural_stamina.description': 'Убежать от того, что должно преследовать',
 'malum.gui.book.entry.void.runes': 'Рунотворчество пустоты',
 'malum.gui.book.entry.void.runes.description': 'Изменённый алфавит',
 'malum.gui.book.entry.void.staves_as_foci': 'Посохи как фокусы',
 'malum.gui.book.entry.void.staves_as_foci.description': 'Подражая аркане',
 'malum.gui.book.entry.void.staves_as_foci.enchanting': 'Зачарование посоха',
 'malum.gui.book.entry.void.staves_as_foci.enchanting.description': 'Подражательная действенность',
 'malum.gui.book.entry.void.staves_as_foci.ring_of_the_endless_well': 'Кольцо неисчерпаемого колодца',
 'malum.gui.book.entry.void.staves_as_foci.ring_of_the_endless_well.description': 'Хранение зарядов посоха',
 'malum.gui.book.entry.void.sundering_anchor': 'Сокрушающий якорь',
 'malum.gui.book.entry.void.sundering_anchor.description': 'Что я ненавижу, то и оно ненавидит вдвойне',
 'malum.gui.book.entry.void.the_weeping_well': 'Плачущий колодец',
 'malum.gui.book.entry.void.the_weeping_well.description': 'Врата в неизвестное',
 'malum.gui.book.entry.void.umbral_arcana': 'Теневая аркана',
 'malum.gui.book.entry.void.umbral_arcana.description': 'Совершенная невозможность',
 'malum.gui.book.entry.void.unwinding_chaos': 'Разматывающийся хаос',
 'malum.gui.book.entry.void.unwinding_chaos.description': 'Умирающая истина ползёт',
 'malum.gui.book.entry.void.weight_of_worlds': 'Тяжесть миров',
 'malum.gui.book.entry.void.weight_of_worlds.description': 'Экзистенциальные тяготы, вынесенные вовне',
 'malum.gui.book.entry.voodoo_magic': 'Магия вуду',
 'malum.gui.book.entry.voodoo_magic.description': 'Создание кукол',
 'malum.gui.book.entry.warping_engine': 'Двигатель искажения',
 'malum.gui.book.entry.warping_engine.description': 'Приостановка линейного времени',
 'malum.gui.book.entry.wicked_rites': 'Скверные ритуалы',
 'malum.gui.book.entry.wicked_rites.description': 'Тотемное искусство вреда',
 'malum.gui.book.entry.windweaving': 'Плетение ветра',
 'malum.gui.book.entry.windweaving.description': 'Формирование воздушных потоков',
 # ---------- заголовки страниц ----------
 'malum.gui.book.entry.page.headline.a_personal_note': 'Личная записка',
 'malum.gui.book.entry.page.headline.a_personal_note.commendations': 'Malum; Благодарности',
 'malum.gui.book.entry.page.headline.a_personal_note.commendations.alphalilly': 'Alphalilly',
 'malum.gui.book.entry.page.headline.a_personal_note.commendations.coalition_of_magic': 'Коалиция магии',
 'malum.gui.book.entry.page.headline.a_personal_note.commendations.kultik': 'Kultik',
 'malum.gui.book.entry.page.headline.a_personal_note.commendations.pessi_mysterio': 'Pessi Mysterio',
 'malum.gui.book.entry.page.headline.a_personal_note.commendations.translation': 'Перевод',
 'malum.gui.book.entry.page.headline.a_personal_note.commendations.wiresegal': 'Wiresegal',
 'malum.gui.book.entry.page.headline.a_personal_note.inspirations': 'Malum; Источники вдохновения',
 'malum.gui.book.entry.page.headline.a_personal_note.inspirations.astral_sorcery': 'Astral Sorcery',
 'malum.gui.book.entry.page.headline.a_personal_note.inspirations.eidolon': 'Eidolon',
 'malum.gui.book.entry.page.headline.a_personal_note.inspirations.mystic_modding': 'Моды Mystic Modding',
 'malum.gui.book.entry.page.headline.a_personal_note.inspirations.thaumcraft': 'Thaumcraft',
 'malum.gui.book.entry.page.headline.accelerating_inlay': 'Ускоряющая вставка',
 'malum.gui.book.entry.page.headline.aerial_rites': 'Воздушные ритуалы',
 'malum.gui.book.entry.page.headline.altar_acceleration.brilliant_obelisk': 'Сияющий обелиск',
 'malum.gui.book.entry.page.headline.altar_acceleration.runewood_obelisk': 'Обелиск из рунного дерева',
 'malum.gui.book.entry.page.headline.aqueous_rites': 'Водные ритуалы',
 'malum.gui.book.entry.page.headline.arcane_restoration': 'Арканное восстановление',
 'malum.gui.book.entry.page.headline.arcane_restoration.tool_repair': 'Починка инструментов',
 'malum.gui.book.entry.page.headline.aura_empowerment': 'Усиление ауры',
 'malum.gui.book.entry.page.headline.aura_empowerment.elemental': 'Усиление ауры',
 'malum.gui.book.entry.page.headline.aura_empowerment.other_pylon_applications': 'Прочие применения пилона',
 'malum.gui.book.entry.page.headline.aura_empowerment.other_pylon_applications.arcane': 'Улучшенное ускорение алтаря',
 'malum.gui.book.entry.page.headline.aura_empowerment.other_pylon_applications.eldritch': 'Элдритческий',
 'malum.gui.book.entry.page.headline.aura_empowerment.other_pylon_applications.sacred': 'Сакральный',
 'malum.gui.book.entry.page.headline.aura_empowerment.other_pylon_applications.wicked': 'Скверный',
 'malum.gui.book.entry.page.headline.authority_of_crushing_melancholy': 'Власть сокрушительной меланхолии',
 'malum.gui.book.entry.page.headline.authority_of_the_gleeful_target': 'Власть радостной мишени',
 'malum.gui.book.entry.page.headline.authority_of_the_inverted_heart': 'Власть обращённого сердца',
 'malum.gui.book.entry.page.headline.basic_artifice': 'Волновое искусство',
 'malum.gui.book.entry.page.headline.basic_artifice.artificers_claw': 'Коготь искусника',
 'malum.gui.book.entry.page.headline.basic_artifice.wavebanker': 'Волнонакопитель',
 'malum.gui.book.entry.page.headline.basic_artifice.wavebreaker': 'Волнопрерыватель',
 'malum.gui.book.entry.page.headline.basic_artifice.wavecharger': 'Волнозарядчик',
 'malum.gui.book.entry.page.headline.basic_artifice.wavemaker': 'Волнообразователь',
 'malum.gui.book.entry.page.headline.belt_of_the_magebane': 'Пояс губителя магов',
 'malum.gui.book.entry.page.headline.belt_of_the_prospector': 'Пояс старателя',
 'malum.gui.book.entry.page.headline.belt_of_the_prospector.avarice': 'Алчность',
 'malum.gui.book.entry.page.headline.belt_of_the_prospector.ring_of_the_demolitionist': 'Кольцо подрывника',
 'malum.gui.book.entry.page.headline.belt_of_the_prospector.ring_of_the_hoarder': 'Кольцо собирателя',
 'malum.gui.book.entry.page.headline.belt_of_the_starved': 'Пояс изголодавшегося',
 'malum.gui.book.entry.page.headline.belt_of_the_starved.concentrated_gluttony': 'Концентрированное чревоугодие',
 'malum.gui.book.entry.page.headline.belt_of_the_starved.ring_of_desperate_voracity': 'Кольцо отчаянной ненасытности',
 'malum.gui.book.entry.page.headline.blazing_diode': 'Пылающий диод',
 'malum.gui.book.entry.page.headline.blazing_quartz': 'Пылающий кварц',
 'malum.gui.book.entry.page.headline.blight.arcane_rite': 'Исследование порчи: резонанс',
 'malum.gui.book.entry.page.headline.blight.composition': 'Исследование порчи: вещество',
 'malum.gui.book.entry.page.headline.blight.flora': 'Исследование порчи: флора',
 'malum.gui.book.entry.page.headline.blight.intro': 'Исследование порчи',
 'malum.gui.book.entry.page.headline.blight.spread': 'Исследование порчи: распространение',
 'malum.gui.book.entry.page.headline.brilliance': 'Сияние',
 'malum.gui.book.entry.page.headline.caustic_catalyst': 'Едкий катализатор',
 'malum.gui.book.entry.page.headline.chronicles_of_the_soul': 'Хроники души',
 'malum.gui.book.entry.page.headline.chronicles_of_the_void': 'Хроники пустоты',
 'malum.gui.book.entry.page.headline.crucible_acceleration': 'Ускорение тигля',
 'malum.gui.book.entry.page.headline.crucible_augmentation': 'Усиление тигля',
 'malum.gui.book.entry.page.headline.cthonic_gold': 'Хтоническое золото',
 'malum.gui.book.entry.page.headline.cthonic_gold.reexamination': 'Переосмысление хтонического золота',
 'malum.gui.book.entry.page.headline.earthen_rites': 'Земляные ритуалы',
 'malum.gui.book.entry.page.headline.elaborate_brooch': 'Затейливая брошь',
 'malum.gui.book.entry.page.headline.eldritch_arcana': 'Элдритческий дух',
 'malum.gui.book.entry.page.headline.elemental_arcana': 'Стихийная аркана',
 'malum.gui.book.entry.page.headline.elemental_arcana.aerial': 'Дух воздуха',
 'malum.gui.book.entry.page.headline.elemental_arcana.aqueous': 'Дух воды',
 'malum.gui.book.entry.page.headline.elemental_arcana.earthen': 'Дух земли',
 'malum.gui.book.entry.page.headline.elemental_arcana.infernal': 'Инфернальный дух',
 'malum.gui.book.entry.page.headline.esoteric_reaping': 'Эзотерическая жатва',
 'malum.gui.book.entry.page.headline.esoteric_reaping.astral_weave': 'Астральное полотно',
 'malum.gui.book.entry.page.headline.esoteric_reaping.grim_talc': 'Мрачный тальк',
 'malum.gui.book.entry.page.headline.esoteric_reaping.rotting_essence': 'Прогнившая эссенция',
 'malum.gui.book.entry.page.headline.esoteric_reaping.warp_flux': 'Поток искажения',
 'malum.gui.book.entry.page.headline.esoteric_reaping.wind_nucleus': 'Ядро ветра',
 'malum.gui.book.entry.page.headline.ether': 'Эфир',
 'malum.gui.book.entry.page.headline.ether.iridescent': 'Переливающийся эфир',
 'malum.gui.book.entry.page.headline.focus_ashes': 'Восстание пепла',
 'malum.gui.book.entry.page.headline.focus_crystals': 'Создание кристаллов',
 'malum.gui.book.entry.page.headline.focus_elemental': 'Воссоздание реликвий',
 'malum.gui.book.entry.page.headline.focus_elemental.zephyr_impetus': 'Импетус ветра',
 'malum.gui.book.entry.page.headline.focus_metals': 'Магия металлов',
 'malum.gui.book.entry.page.headline.fragment.void.black_crystal': 'Нацарапанные записи',
 'malum.gui.book.entry.page.headline.fragment.void.umbral_arcana': 'Странные уравнения',
 'malum.gui.book.entry.page.headline.geas_magic': 'Геасы и прочие клятвы',
 'malum.gui.book.entry.page.headline.glass_brooch': 'Стеклянная брошь',
 'malum.gui.book.entry.page.headline.gluttonous_brooch': 'Прожорливая брошь',
 'malum.gui.book.entry.page.headline.impurity_stabilizer': 'Стабилизатор примесей',
 'malum.gui.book.entry.page.headline.infernal_rites': 'Инфернальные ритуалы',
 'malum.gui.book.entry.page.headline.intricate_assembly': 'Замысловатая сборка',
 'malum.gui.book.entry.page.headline.introduction': 'Введение',
 'malum.gui.book.entry.page.headline.locus_management': 'Управление очагом',
 'malum.gui.book.entry.page.headline.locus_management.aerial': 'Скорость очага',
 'malum.gui.book.entry.page.headline.locus_management.aqueous': 'Мощь очага',
 'malum.gui.book.entry.page.headline.locus_management.arcane': 'Перенаправление очага',
 'malum.gui.book.entry.page.headline.locus_management.earthen': 'Удар очага',
 'malum.gui.book.entry.page.headline.locus_management.eldritch': 'Разъединение с очагом',
 'malum.gui.book.entry.page.headline.locus_management.elemental_boons': 'Исследование ритуала: стихийные дары',
 'malum.gui.book.entry.page.headline.locus_management.infernal': 'Дальность очага',
 'malum.gui.book.entry.page.headline.locus_management.sacred': 'Восстановление очага',
 'malum.gui.book.entry.page.headline.locus_management.wicked': 'Воскрешение очага',
 'malum.gui.book.entry.page.headline.locus_management.wicked_order': 'Исследование ритуала: воскрешение очага',
 'malum.gui.book.entry.page.headline.managing_totems': 'Резонанс тотема',
 'malum.gui.book.entry.page.headline.mending_diffuser': 'Диффузор починки',
 'malum.gui.book.entry.page.headline.mirror_magic': 'Магия зеркал',
 'malum.gui.book.entry.page.headline.mote_making': 'Создание частиц',
 'malum.gui.book.entry.page.headline.natural_quartz': 'Природный кварц',
 'malum.gui.book.entry.page.headline.necklace_of_blissful_harmony': 'Ожерелье блаженной гармонии',
 'malum.gui.book.entry.page.headline.necklace_of_the_mystic_mirror': 'Ожерелье мистического зеркала',
 'malum.gui.book.entry.page.headline.necklace_of_the_narrow_edge': 'Ожерелье узкой грани',
 'malum.gui.book.entry.page.headline.necklace_of_the_narrow_edge.ring_of_the_howling_maelstrom': 'Воющий водоворот',
 'malum.gui.book.entry.page.headline.necklace_of_the_narrow_edge.ring_of_the_rising_edge': 'Восходящая грань',
 'malum.gui.book.entry.page.headline.oath_of_the_overburdened_mind': 'Клятва обременённого разума',
 'malum.gui.book.entry.page.headline.oath_of_the_overeager_fist': 'Клятва слишком рьяного кулака',
 'malum.gui.book.entry.page.headline.oath_of_the_overkeen_eye': 'Клятва слишком зоркого глаза',
 'malum.gui.book.entry.page.headline.oath_of_the_undiscerned_maw': 'Клятва неразличимой утробы',
 'malum.gui.book.entry.page.headline.oath_of_unmakers_disdain': 'Клятва презрения разрушителя',
 'malum.gui.book.entry.page.headline.oath_of_unsighted_resistance': 'Клятва незрячего сопротивления',
 'malum.gui.book.entry.page.headline.pact_of_combustion': 'Пакт горения',
 'malum.gui.book.entry.page.headline.pact_of_contentedness': 'Пакт довольства',
 'malum.gui.book.entry.page.headline.pact_of_defiance': 'Пакт непокорности',
 'malum.gui.book.entry.page.headline.pact_of_patience_repaid': 'Пакт возданного терпения',
 'malum.gui.book.entry.page.headline.pact_of_reciprocation': 'Пакт взаимности',
 'malum.gui.book.entry.page.headline.pact_of_rune_exploitation': 'Пакт использования рун',
 'malum.gui.book.entry.page.headline.pact_of_self_care': 'Пакт заботы о себе',
 'malum.gui.book.entry.page.headline.pact_of_the_arcanaphage': 'Пакт арканофага',
 'malum.gui.book.entry.page.headline.pact_of_the_berserker': 'Пакт берсерка',
 'malum.gui.book.entry.page.headline.pact_of_the_blastweaver': 'Пакт ткача взрывов',
 'malum.gui.book.entry.page.headline.pact_of_the_cloudskipper': 'Пакт скачущего по облакам',
 'malum.gui.book.entry.page.headline.pact_of_the_continuing_shot': 'Пакт непрерывного выстрела',
 'malum.gui.book.entry.page.headline.pact_of_the_fortress': 'Пакт крепости',
 'malum.gui.book.entry.page.headline.pact_of_the_high_priest': 'Пакт верховного жреца',
 'malum.gui.book.entry.page.headline.pact_of_the_lifeweaver': 'Пакт ткача жизни',
 'malum.gui.book.entry.page.headline.pact_of_the_lone_druid': 'Пакт одинокого друида',
 'malum.gui.book.entry.page.headline.pact_of_the_parasite': 'Пакт паразита',
 'malum.gui.book.entry.page.headline.pact_of_the_profane_ascetic': 'Пакт нечестивого аскета',
 'malum.gui.book.entry.page.headline.pact_of_the_profane_glutton': 'Пакт нечестивого чревоугодника',
 'malum.gui.book.entry.page.headline.pact_of_the_prospector': 'Пакт старателя',
 'malum.gui.book.entry.page.headline.pact_of_the_reaper': 'Пакт жнеца',
 'malum.gui.book.entry.page.headline.pact_of_the_shattering_addict': 'Пакт зависимости от раскалывания',
 'malum.gui.book.entry.page.headline.pact_of_the_shield': 'Пакт щита',
 'malum.gui.book.entry.page.headline.pact_of_the_skybreaker': 'Пакт разящего небеса',
 'malum.gui.book.entry.page.headline.pact_of_the_warlock': 'Пакт колдуна',
 'malum.gui.book.entry.page.headline.pact_of_the_windswept': 'Пакт овеянного ветром',
 'malum.gui.book.entry.page.headline.pact_of_tidal_affinity': 'Пакт приливного родства',
 'malum.gui.book.entry.page.headline.pact_of_wyrd_reconstruction': 'Пакт восстановления вирдом',
 'malum.gui.book.entry.page.headline.pacts_of_an_igneous_shaper': 'Пакты магматического ваятеля',
 'malum.gui.book.entry.page.headline.pacts_of_an_inward_soul': 'Пакты обращённой внутрь души',
 'malum.gui.book.entry.page.headline.pacts_of_an_unbound_wayfarer': 'Пакт свободного странника',
 'malum.gui.book.entry.page.headline.pacts_of_an_uneven_conscience': 'Пакт неровной совести',
 'malum.gui.book.entry.page.headline.primary_arcana.arcane': 'Арканный дух',
 'malum.gui.book.entry.page.headline.primary_arcana.sacred': 'Сакральный дух',
 'malum.gui.book.entry.page.headline.primary_arcana.wicked': 'Скверный дух',
 'malum.gui.book.entry.page.headline.prismatic_focus_lens': 'Призматическая фокусная линза',
 'malum.gui.book.entry.page.headline.reactive_trinkets.ring_of_alchemical_mastery': 'Кольцо алхимического мастерства',
 'malum.gui.book.entry.page.headline.reactive_trinkets.ring_of_curative_talent': 'Кольцо целительного дара',
 'malum.gui.book.entry.page.headline.reactive_trinkets.ring_of_manaweaving': 'Кольцо плетения маны',
 'malum.gui.book.entry.page.headline.reactive_trinkets.ring_of_prowess': 'Кольцо мастерства',
 'malum.gui.book.entry.page.headline.resonance_tuner': 'Настройщик резонанса',
 'malum.gui.book.entry.page.headline.ring_of_esoteric_spoils': 'Кольцо эзотерических трофеев',
 'malum.gui.book.entry.page.headline.ritual_magic': 'Ритуальная магия',
 'malum.gui.book.entry.page.headline.rune_of_ailment_cleansing': 'Руна очищения от недугов',
 'malum.gui.book.entry.page.headline.rune_of_burning_fervor': 'Руна пылающего рвения',
 'malum.gui.book.entry.page.headline.rune_of_culling': 'Руна добивания',
 'malum.gui.book.entry.page.headline.rune_of_dexterity': 'Руна ловкости',
 'malum.gui.book.entry.page.headline.rune_of_fiery_embrace': 'Руна огненных объятий',
 'malum.gui.book.entry.page.headline.rune_of_flowing_grasp': 'Руна текучей хватки',
 'malum.gui.book.entry.page.headline.rune_of_good_tides': 'Руна благоприятных приливов',
 'malum.gui.book.entry.page.headline.rune_of_howling_gale': 'Руна воющего шквала',
 'malum.gui.book.entry.page.headline.rune_of_oaken_might': 'Руна дубовой мощи',
 'malum.gui.book.entry.page.headline.rune_of_protection': 'Руна защиты',
 'malum.gui.book.entry.page.headline.rune_of_reinforcement': 'Руна подкрепления',
 'malum.gui.book.entry.page.headline.rune_of_scorching': 'Руна опаления',
 'malum.gui.book.entry.page.headline.rune_of_sky_tether': 'Руна небесного поводка',
 'malum.gui.book.entry.page.headline.rune_of_stone_ward': 'Руна каменной защиты',
 'malum.gui.book.entry.page.headline.rune_of_vitality': 'Руна живучести',
 'malum.gui.book.entry.page.headline.rune_of_volatile_distortion': 'Руна нестабильного искажения',
 'malum.gui.book.entry.page.headline.runewood': 'Рунное дерево',
 'malum.gui.book.entry.page.headline.runewood.arcane_charcoal': 'Арканный древесный уголь',
 'malum.gui.book.entry.page.headline.runewood.runic_sap': 'Рунический сок',
 'malum.gui.book.entry.page.headline.runeworking': 'Создание рун',
 'malum.gui.book.entry.page.headline.runic_brooch': 'Руническая брошь',
 'malum.gui.book.entry.page.headline.sacred_rites': 'Сакральные ритуалы',
 'malum.gui.book.entry.page.headline.scarstone': 'Исследование камня шрамов',
 'malum.gui.book.entry.page.headline.scarstone.creation': 'Исследование камня шрамов: создание',
 'malum.gui.book.entry.page.headline.scarstone.material': 'Исследование камня шрамов: материал',
 'malum.gui.book.entry.page.headline.scarstone.strange_crystal': 'Исследование камня шрамов: странный кристалл',
 'malum.gui.book.entry.page.headline.scythes': 'Косы',
 'malum.gui.book.entry.page.headline.scythes.enchanting': 'Зачарование косы',
 'malum.gui.book.entry.page.headline.scythes.enchanting.animated': 'Одушевлённый',
 'malum.gui.book.entry.page.headline.scythes.enchanting.ascension': 'Восхождение',
 'malum.gui.book.entry.page.headline.scythes.enchanting.haunted': 'Преследуемый',
 'malum.gui.book.entry.page.headline.scythes.enchanting.rebound': 'Отскок',
 'malum.gui.book.entry.page.headline.scythes.enchanting.spirit_plunder': 'Ограбление духов',
 'malum.gui.book.entry.page.headline.shielding_apparatus': 'Защитное устройство',
 'malum.gui.book.entry.page.headline.soulhunter_armor': 'Броня охотника за душами',
 'malum.gui.book.entry.page.headline.soulstained_armor': 'Броня из духостали',
 'malum.gui.book.entry.page.headline.soulstained_scythe': 'Коса из духостали',
 'malum.gui.book.entry.page.headline.soulstone': 'Камень душ',
 'malum.gui.book.entry.page.headline.soulwood': 'Исследование дерева душ',
 'malum.gui.book.entry.page.headline.soulwood.blight': 'Исследование дерева душ: порча',
 'malum.gui.book.entry.page.headline.soulwood.bonemeal': 'Исследование дерева душ: рост',
 'malum.gui.book.entry.page.headline.soulwood.cursed_sap': 'Исследование дерева душ: сок',
 'malum.gui.book.entry.page.headline.soulwoven_pouch': 'Мешочек, сотканный из душ',
 'malum.gui.book.entry.page.headline.soulwoven_pouch.ravenous_pouch': 'Ненасытный мешочек',
 'malum.gui.book.entry.page.headline.soulwoven_silk': 'Шёлк, сотканный из душ',
 'malum.gui.book.entry.page.headline.spellweaving_axe': 'Топор плетения заклинаний',
 'malum.gui.book.entry.page.headline.spellweaving_pickaxe': 'Кирка плетения заклинаний',
 'malum.gui.book.entry.page.headline.spellweaving_tools.enchanting': 'Зачарование сотканного',
 'malum.gui.book.entry.page.headline.spellweaving_tools.enchanting.weavers_haste': 'Спешка ткача',
 'malum.gui.book.entry.page.headline.spellweaving_tools.enchanting.weavers_propagation': 'Распространение ткача',
 'malum.gui.book.entry.page.headline.spirit_crystals': 'Кристаллы духов',
 'malum.gui.book.entry.page.headline.spirit_focusing': 'Фокусировка духов',
 'malum.gui.book.entry.page.headline.spirit_infusion': 'Насыщение духами',
 'malum.gui.book.entry.page.headline.spirit_infusion.alchemical_calx': 'Алхимическая окалина',
 'malum.gui.book.entry.page.headline.spirit_infusion.hex_ash': 'Колдовской пепел',
 'malum.gui.book.entry.page.headline.spirit_infusion.living_flesh': 'Живая плоть',
 'malum.gui.book.entry.page.headline.spirit_jar': 'Банка для духов',
 'malum.gui.book.entry.page.headline.spirit_metals.hallowed_gold': 'Священное золото',
 'malum.gui.book.entry.page.headline.spirit_metals.reexamination': 'Переосмысление металлов духов',
 'malum.gui.book.entry.page.headline.spirit_metals.soul_stained_steel': 'Духосталь',
 'malum.gui.book.entry.page.headline.spirit_minerals.reexamination': 'Переосмысление минералов духов',
 'malum.gui.book.entry.page.headline.spirit_stones.reexamination': 'Переосмысление камней духов',
 'malum.gui.book.entry.page.headline.spirit_stones.tainted_rock': 'Осквернённый камень',
 'malum.gui.book.entry.page.headline.spirit_stones.twisted_rock': 'Искажённый камень',
 'malum.gui.book.entry.page.headline.spirit_trinkets': 'Аксессуары духов',
 'malum.gui.book.entry.page.headline.spirited_glass': 'Стекло духов',
 'malum.gui.book.entry.page.headline.strange_crystal.material': 'Исследование странного кристалла: материал',
 'malum.gui.book.entry.page.headline.strange_crystal.purpose': 'Исследование странного кристалла: назначение',
 'malum.gui.book.entry.page.headline.strange_crystal.reexamination': 'Переосмысление странных кристаллов',
 'malum.gui.book.entry.page.headline.strange_crystal.revelation': 'Раскрытие странных кристаллов',
 'malum.gui.book.entry.page.headline.suspicious_device': 'Подозрительное устройство',
 'malum.gui.book.entry.page.headline.sympathy_drive': 'Привод симпатии',
 'malum.gui.book.entry.page.headline.the_device': 'Устройство.',
 'malum.gui.book.entry.page.headline.totem_magic': 'Магия тотемов',
 'malum.gui.book.entry.page.headline.totem_magic.waveform_totemancy': 'Волновая тотемантия',
 'malum.gui.book.entry.page.headline.tyrving': 'Тирвинг',
 'malum.gui.book.entry.page.headline.unchained_rite': 'Освобождённый ритуал',
 'malum.gui.book.entry.page.headline.unchained_rite.soulwood': 'Трансмутация дерева душ',
 'malum.gui.book.entry.page.headline.unchained_transmutation': 'Освобождённая трансмутация',
 'malum.gui.book.entry.page.headline.unchained_transmutation.basalt': 'Сжигание без жара',
 'malum.gui.book.entry.page.headline.unchained_transmutation.deepslate': 'Серые камни',
 'malum.gui.book.entry.page.headline.unchained_transmutation.dirt': 'Рост без семян',
 'malum.gui.book.entry.page.headline.unchained_transmutation.mud': 'Насыщение без влаги',
 'malum.gui.book.entry.page.headline.unchained_transmutation.packed_mud': 'Оранжевые камни',
 'malum.gui.book.entry.page.headline.unchained_transmutation.snow': 'Белые камни',
 'malum.gui.book.entry.page.headline.unchained_transmutation.stone': 'Измельчение без усилия',
 'malum.gui.book.entry.page.headline.undirected_rite': 'Ненаправленный ритуал',
 'malum.gui.book.entry.page.headline.undoing_geas_bindings': 'Отречение от геасов',
 'malum.gui.book.entry.page.headline.varnished_terracotta': 'Глазурованная терракота',
 'malum.gui.book.entry.page.headline.void.belt_of_the_limitless': 'Пояс безграничности',
 'malum.gui.book.entry.page.headline.void.black_crystal': 'Чёрный кристалл',
 'malum.gui.book.entry.page.headline.void.catalyst_lobber': 'Метатель катализаторов',
 'malum.gui.book.entry.page.headline.void.edge_of_deliverance': 'Грань избавления',
 'malum.gui.book.entry.page.headline.void.erosion_scepter': 'Скипетр эрозии',
 'malum.gui.book.entry.page.headline.void.fused_consciousness': 'Слитое сознание',
 'malum.gui.book.entry.page.headline.void.inverse_and_hybrid_arcana': 'Теоретическая аркана',
 'malum.gui.book.entry.page.headline.void.malignant_pewter': 'Злокачественный пьютер',
 'malum.gui.book.entry.page.headline.void.malignant_stronghold_armor': 'Броня злокачественной твердыни',
 'malum.gui.book.entry.page.headline.void.material_study_arcana': 'Исследование: кристалл духов',
 'malum.gui.book.entry.page.headline.void.material_study_auric_embers': 'Исследование: золотистый уголь',
 'malum.gui.book.entry.page.headline.void.material_study_auric_embers.reexamination': 'Переосмысление: золотистый уголь',
 'malum.gui.book.entry.page.headline.void.material_study_malignant_lead': 'Исследование: злокачественный свинец',
 'malum.gui.book.entry.page.headline.void.material_study_malignant_lead.reexamination': 'Переосмысление злокачественного свинца',
 'malum.gui.book.entry.page.headline.void.material_study_mnemonic_fragment': 'Исследование: Мнемозина',
 'malum.gui.book.entry.page.headline.void.material_study_mnemonic_fragment.reexamination': 'Переосмысление: Мнемозина',
 'malum.gui.book.entry.page.headline.void.material_study_null_slate': 'Исследование: пустая скрижаль',
 'malum.gui.book.entry.page.headline.void.material_study_null_slate.reexamination': 'Переосмысление: пустая скрижаль',
 'malum.gui.book.entry.page.headline.void.material_study_soulstone': 'Исследование: камень душ',
 'malum.gui.book.entry.page.headline.void.material_study_void_salts': 'Исследование: пустотная соль',
 'malum.gui.book.entry.page.headline.void.material_study_void_salts.reexamination': 'Переосмысление: пустотная соль',
 'malum.gui.book.entry.page.headline.void.necklace_of_the_hidden_blade': 'Ожерелье скрытого клинка',
 'malum.gui.book.entry.page.headline.void.necklace_of_the_watcher': 'Ожерелье наблюдателя',
 'malum.gui.book.entry.page.headline.void.ring_of_echoing_arcana': 'Кольцо эха арканы',
 'malum.gui.book.entry.page.headline.void.ring_of_growing_flesh': 'Кольцо растущей плоти',
 'malum.gui.book.entry.page.headline.void.ring_of_gruesome_concentration': 'Кольцо жуткой концентрации',
 'malum.gui.book.entry.page.headline.void.rune_of_bolstering': 'Руна укрепления',
 'malum.gui.book.entry.page.headline.void.rune_of_heresy': 'Руна ереси',
 'malum.gui.book.entry.page.headline.void.rune_of_igneous_solace': 'Руна огненного утешения',
 'malum.gui.book.entry.page.headline.void.rune_of_indomitability': 'Руна неукротимости',
 'malum.gui.book.entry.page.headline.void.rune_of_radial_empowerment': 'Жертвенное усиление',
 'malum.gui.book.entry.page.headline.void.rune_of_spell_mastery': 'Руна мастерства заклинаний',
 'malum.gui.book.entry.page.headline.void.rune_of_twinned_duration': 'Руна двойной длительности',
 'malum.gui.book.entry.page.headline.void.rune_of_unnatural_stamina': 'Руна противоестественной выносливости',
 'malum.gui.book.entry.page.headline.void.runes': 'Рунотворчество пустоты',
 'malum.gui.book.entry.page.headline.void.staves_as_foci': 'Посохи как фокусы',
 'malum.gui.book.entry.page.headline.void.staves_as_foci.enchanting.capacitor': 'Конденсатор',
 'malum.gui.book.entry.page.headline.void.staves_as_foci.enchanting.replenishing': 'Восполнение',
 'malum.gui.book.entry.page.headline.void.staves_as_foci.ring_of_the_endless_well': 'Кольцо неисчерпаемого колодца',
 'malum.gui.book.entry.page.headline.void.sundering_anchor': 'Сокрушающий якорь',
 'malum.gui.book.entry.page.headline.void.the_weeping_well': 'Плачущий колодец',
 'malum.gui.book.entry.page.headline.void.umbral_arcana': 'Теневая аркана',
 'malum.gui.book.entry.page.headline.void.unwinding_chaos': 'Разматывающийся хаос',
 'malum.gui.book.entry.page.headline.void.weight_of_worlds': 'Тяжесть миров',
 'malum.gui.book.entry.page.headline.voodoo_magic': 'Магия вуду',
 'malum.gui.book.entry.page.headline.warping_engine': 'Двигатель искажения',
 'malum.gui.book.entry.page.headline.wicked_rites': 'Скверные ритуалы',
 'malum.gui.book.entry.page.headline.windweaving': 'Плетение ветра',
 'malum.gui.book.entry.page.headline.windweaving.gust_igniter': 'Зажигатель порывов',
 'malum.gui.book.entry.page.headline.windweaving.wind_tunnel': 'Ветряной тоннель',
 # ---------- информационные блоки ----------
 'malum.gui.book.entry.page.info.runeworking': 'Вставьте скрижаль в рунический верстак\nИспользуйте аркану духов, чтобы нанести руны на скрижаль',
 'malum.gui.book.entry.page.info.runeworking.headline': 'Создание рун',
 'malum.gui.book.entry.page.info.soul_binding': 'Поместите основной предмет, аркану духов и прочие предметы в жаровню связывания душ\nПроцесс запускает эфирное подношение',
 'malum.gui.book.entry.page.info.soul_binding.headline': 'Связывание душ',
 'malum.gui.book.entry.page.info.spirit_focusing': 'Поместите катализатор и аркану духов в тигель\nКатализатор частично расходуется с каждым циклом фокусировки',
 'malum.gui.book.entry.page.info.spirit_focusing.headline': 'Фокусировка духов',
 'malum.gui.book.entry.page.info.spirit_infusion': 'Поместите основной предмет и аркану духов в алтарь духов\nРазложите дополнительные предметы на ближайших подставках для предметов',
 'malum.gui.book.entry.page.info.spirit_infusion.headline': 'Насыщение духами',
 'malum.gui.book.entry.page.info.spirit_repair': 'Поместите материал для починки и аркану духов в пилон починки\nПовреждённый предмет нужно положить на ближайшую подставку для предметов',
 'malum.gui.book.entry.page.info.spirit_repair.headline': 'Починка духами',
 'malum.gui.book.entry.page.info.unchained_transmutation': 'С помощью очага ритуала превращайте блоки в другие блоки через освобождённый ритуал\nОчагу ритуала нужна порча как проводник',
 'malum.gui.book.entry.page.info.unchained_transmutation.headline': 'Освобождённая трансмутация',
 'malum.gui.book.entry.page.info.unchained_transmutation_tree': 'С помощью очага ритуала превращайте блоки в другие блоки через освобождённый ритуал\nОчагу ритуала нужна порча как проводник\nТрансмутация следует показанному древу трансмутации\nЛюбой элемент древа можно взять за отправную точку',
 'malum.gui.book.entry.page.info.unchained_transmutation_tree.headline': 'Освобождённая трансмутация',
}
