# -*- coding: utf-8 -*-
# Malum, часть 2: блоки.
P2 = {
 # ---- стекло и терракота по стихиям ----
 'block.malum.aerial_spirited_glass': 'Стекло духа воздуха',
 'block.malum.aerial_varnished_terracotta': 'Глазурованная терракота духа воздуха',
 'block.malum.aqueous_spirited_glass': 'Стекло духа воды',
 'block.malum.aqueous_varnished_terracotta': 'Глазурованная терракота духа воды',
 'block.malum.arcane_spirited_glass': 'Стекло арканного духа',
 'block.malum.arcane_varnished_terracotta': 'Глазурованная терракота арканного духа',
 'block.malum.earthen_spirited_glass': 'Стекло духа земли',
 'block.malum.earthen_varnished_terracotta': 'Глазурованная терракота духа земли',
 'block.malum.eldritch_spirited_glass': 'Стекло элдритческого духа',
 'block.malum.eldritch_varnished_terracotta': 'Глазурованная терракота элдритческого духа',
 'block.malum.infernal_spirited_glass': 'Стекло инфернального духа',
 'block.malum.infernal_varnished_terracotta': 'Глазурованная терракота инфернального духа',
 'block.malum.sacred_spirited_glass': 'Стекло сакрального духа',
 'block.malum.sacred_varnished_terracotta': 'Глазурованная терракота сакрального духа',
 'block.malum.wicked_spirited_glass': 'Стекло скверного духа',
 'block.malum.wicked_varnished_terracotta': 'Глазурованная терракота скверного духа',
 # ---- устройства магии ----
 'block.malum.arcana_pylon': 'Пилон арканы',
 'block.malum.arcana_pylon_component': 'Компонент пилона арканы',
 'block.malum.brilliant_obelisk': 'Сияющий обелиск',
 'block.malum.brilliant_obelisk_component': 'Компонент сияющего обелиска',
 'block.malum.repair_pylon': 'Пилон починки',
 'block.malum.repair_pylon_component': 'Компонент пилона починки',
 'block.malum.runewood_obelisk': 'Обелиск из рунного дерева',
 'block.malum.runewood_obelisk_component': 'Компонент обелиска из рунного дерева',
 'block.malum.spirit_altar': 'Алтарь духов',
 'block.malum.spirit_catalyzer': 'Катализатор духов',
 'block.malum.spirit_catalyzer_component': 'Компонент катализатора духов',
 'block.malum.spirit_crucible': 'Тигель духов',
 'block.malum.spirit_crucible_component': 'Компонент тигля духов',
 'block.malum.spirit_jar': 'Банка для духов',
 'block.malum.spirit_mote': 'Частица духа',
 'block.malum.soulbinding_brazier': 'Жаровня связывания душ',
 'block.malum.rite_anchor': 'Якорь ритуала',
 'block.malum.rite_unweaver': 'Расплетатель ритуала',
 'block.malum.ritual_plinth': 'Ритуальный постамент',
 'block.malum.runic_workbench': 'Рунический верстак',
 'block.malum.weavers_workbench': 'Верстак ткача',
 'block.malum.runewood_item_pedestal': 'Пьедестал из рунного дерева',
 'block.malum.runewood_item_stand': 'Подставка из рунного дерева',
 'block.malum.gilded_runewood_item_pedestal': 'Позолоченный пьедестал из рунного дерева',
 'block.malum.gilded_runewood_item_stand': 'Позолоченная подставка из рунного дерева',
 'block.malum.soulwood_item_pedestal': 'Пьедестал из дерева души',
 'block.malum.soulwood_item_stand': 'Подставка из дерева души',
 'block.malum.ornate_soulwood_item_pedestal': 'Изысканный пьедестал из дерева души',
 'block.malum.ornate_soulwood_item_stand': 'Изысканная подставка из дерева души',
 'block.malum.tainted_rock_item_pedestal': 'Пьедестал из осквернённого камня',
 'block.malum.tainted_rock_item_stand': 'Подставка из осквернённого камня',
 'block.malum.twisted_rock_item_pedestal': 'Пьедестал из искажённого камня',
 'block.malum.twisted_rock_item_stand': 'Подставка из искажённого камня',
 # ---- руды, грозди, камни ----
 'block.malum.blazing_quartz_ore': 'Руда пылающего кварца',
 'block.malum.blazing_quartz_cluster': 'Гроздь пылающего кварца',
 'block.malum.natural_quartz_ore': 'Руда природного кварца',
 'block.malum.natural_quartz_cluster': 'Гроздь природного кварца',
 'block.malum.cthonic_gold_ore': 'Руда хтонического золота',
 'block.malum.cthonic_gold_cluster': 'Гроздь хтонического золота',
 'block.malum.soulstone_ore': 'Руда камня душ',
 'block.malum.deepslate_quartz_ore': 'Глубиносланцевая кварцевая руда',
 'block.malum.deepslate_soulstone_ore': 'Глубиносланцевая руда камня душ',
 'block.malum.brilliant_stone': 'Сияющий камень',
 'block.malum.brilliant_deepslate': 'Сияющий глубинный сланец',
 'block.malum.strange_crystal': 'Странный кристалл',
 'block.malum.large_strange_crystal': 'Большой странный кристалл',
 'block.malum.scarstone': 'Камень шрамов',
 # ---- скверна и растения ----
 'block.malum.blight': 'Порча',
 'block.malum.clinging_blight': 'Цепляющаяся порча',
 'block.malum.blighted_earth': 'Сгнившая земля',
 'block.malum.blighted_growth': 'Сгнившая поросль',
 'block.malum.blighted_soulwood': 'Сгнившее дерево душ',
 'block.malum.mass_of_blighted_gunk': 'Ком сгнившей слизи',
 'block.malum.blightpearl': 'Жемчужина порчи',
 'block.malum.blightroot': 'Корень порчи',
 'block.malum.strangeroot': 'Странный корень',
 'block.malum.potted_runewood_sapling': 'Саженец рунного дерева в горшке',
 'block.malum.potted_azure_runewood_sapling': 'Лазурный саженец рунного дерева в горшке',
 'block.malum.potted_soulwood_sapling': 'Саженец дерева души в горшке',
 'block.malum.potted_blightpearl': 'Жемчужина порчи в горшке',
 'block.malum.potted_blightroot': 'Корень порчи в горшке',
 'block.malum.potted_strangeroot': 'Странный корень в горшке',
 # ---- блоки из материалов ----
 'block.malum.block_of_alchemical_calx': 'Блок алхимической окалины',
 'block.malum.block_of_arcane_charcoal': 'Блок арканного древесного угля',
 'block.malum.block_of_astral_weave': 'Блок астрального полотна',
 'block.malum.block_of_auric_embers': 'Блок золотистых углей',
 'block.malum.block_of_blazing_quartz': 'Блок пылающего кварца',
 'block.malum.block_of_brilliance': 'Блок сияния',
 'block.malum.block_of_cthonic_gold': 'Блок хтонического золота',
 'block.malum.block_of_grim_talc': 'Блок мрачного талька',
 'block.malum.block_of_hallowed_gold': 'Блок священного золота',
 'block.malum.block_of_hex_ash': 'Блок колдовского пепла',
 'block.malum.block_of_living_flesh': 'Блок живой плоти',
 'block.malum.block_of_malignant_lead': 'Блок злокачественного свинца',
 'block.malum.block_of_malignant_pewter': 'Блок злокачественного пьютера',
 'block.malum.block_of_mnemonic_fragment': 'Блок мнемонического фрагмента',
 'block.malum.block_of_null_slate': 'Блок пустой скрижали',
 'block.malum.block_of_raw_soulstone': 'Блок сырого камня душ',
 'block.malum.block_of_rotting_essence': 'Блок прогнившей эссенции',
 'block.malum.block_of_soul_stained_steel': 'Блок духостали',
 'block.malum.block_of_soulstone': 'Блок камня душ',
 'block.malum.block_of_void_salts': 'Блок пустотной соли',
 'block.malum.block_of_warp_flux': 'Блок потока искажения',
 # ---- эфир ----
 'block.malum.ether': 'Эфир',
 'block.malum.ether_torch': 'Эфирный факел',
 'block.malum.iridescent_ether': 'Переливающийся эфир',
 'block.malum.iridescent_ether_torch': 'Переливающийся эфирный факел',
 'block.malum.tainted_ether_brazier': 'Жаровня осквернённого эфира',
 'block.malum.tainted_iridescent_ether_brazier': 'Жаровня осквернённого переливающегося эфира',
 'block.malum.twisted_ether_brazier': 'Жаровня искажённого эфира',
 'block.malum.twisted_iridescent_ether_brazier': 'Жаровня искажённого переливающегося эфира',
 # ---- осквернённый и искажённый камень ----
 'block.malum.tainted_rock': 'Осквернённый камень',
 'block.malum.twisted_rock': 'Искажённый камень',
 'block.malum.chiseled_tainted_rock': 'Высеченный осквернённый камень',
 'block.malum.chiseled_twisted_rock': 'Высеченный искажённый камень',
 'block.malum.checkered_tainted_rock': 'Клетчатый осквернённый камень',
 'block.malum.checkered_twisted_rock': 'Клетчатый искажённый камень',
 'block.malum.cut_tainted_rock': 'Обработанный осквернённый камень',
 'block.malum.cut_twisted_rock': 'Обработанный искажённый камень',
 'block.malum.smooth_tainted_rock': 'Гладкий осквернённый камень',
 'block.malum.smooth_tainted_rock_slab': 'Плита из гладкого осквернённого камня',
 'block.malum.smooth_tainted_rock_stairs': 'Ступеньки из гладкого осквернённого камня',
 'block.malum.smooth_tainted_rock_wall': 'Ограда из гладкого осквернённого камня',
 'block.malum.smooth_twisted_rock': 'Гладкий искажённый камень',
 'block.malum.smooth_twisted_rock_slab': 'Плита из гладкого искажённого камня',
 'block.malum.smooth_twisted_rock_stairs': 'Ступеньки из гладкого искажённого камня',
 'block.malum.smooth_twisted_rock_wall': 'Ограда из гладкого искажённого камня',
 'block.malum.polished_tainted_rock': 'Полированный осквернённый камень',
 'block.malum.polished_tainted_rock_slab': 'Плита из полированного осквернённого камня',
 'block.malum.polished_tainted_rock_stairs': 'Ступеньки из полированного осквернённого камня',
 'block.malum.polished_tainted_rock_wall': 'Ограда из полированного осквернённого камня',
 'block.malum.polished_twisted_rock': 'Полированный искажённый камень',
 'block.malum.polished_twisted_rock_slab': 'Плита из полированного искажённого камня',
 'block.malum.polished_twisted_rock_stairs': 'Ступеньки из полированного искажённого камня',
 'block.malum.polished_twisted_rock_wall': 'Ограда из полированного искажённого камня',
 'block.malum.tainted_rock_bricks': 'Кирпичи из осквернённого камня',
 'block.malum.tainted_rock_bricks_slab': 'Плита из кирпичей осквернённого камня',
 'block.malum.tainted_rock_bricks_stairs': 'Ступеньки из кирпичей осквернённого камня',
 'block.malum.tainted_rock_bricks_wall': 'Ограда из кирпичей осквернённого камня',
 'block.malum.twisted_rock_bricks': 'Кирпичи из искажённого камня',
 'block.malum.twisted_rock_bricks_slab': 'Плита из кирпичей искажённого камня',
 'block.malum.twisted_rock_bricks_stairs': 'Ступеньки из кирпичей искажённого камня',
 'block.malum.twisted_rock_bricks_wall': 'Ограда из кирпичей искажённого камня',
 'block.malum.small_tainted_rock_bricks': 'Мелкие кирпичи из осквернённого камня',
 'block.malum.small_tainted_rock_bricks_slab': 'Плита из мелких кирпичей осквернённого камня',
 'block.malum.small_tainted_rock_bricks_stairs': 'Ступеньки из мелких кирпичей осквернённого камня',
 'block.malum.small_tainted_rock_bricks_wall': 'Ограда из мелких кирпичей осквернённого камня',
 'block.malum.small_twisted_rock_bricks': 'Мелкие кирпичи из искажённого камня',
 'block.malum.small_twisted_rock_bricks_slab': 'Плита из мелких кирпичей искажённого камня',
 'block.malum.small_twisted_rock_bricks_stairs': 'Ступеньки из мелких кирпичей искажённого камня',
 'block.malum.small_twisted_rock_bricks_wall': 'Ограда из мелких кирпичей искажённого камня',
 'block.malum.tainted_rock_tiles': 'Плитняк из осквернённого камня',
 'block.malum.tainted_rock_tiles_slab': 'Плита из плитняка осквернённого камня',
 'block.malum.tainted_rock_tiles_stairs': 'Ступеньки из плитняка осквернённого камня',
 'block.malum.tainted_rock_tiles_wall': 'Ограда из плитняка осквернённого камня',
 'block.malum.twisted_rock_tiles': 'Плитняк из искажённого камня',
 'block.malum.twisted_rock_tiles_slab': 'Плита из плитняка искажённого камня',
 'block.malum.twisted_rock_tiles_stairs': 'Ступеньки из плитняка искажённого камня',
 'block.malum.twisted_rock_tiles_wall': 'Ограда из плитняка искажённого камня',
 'block.malum.tainted_rock_column': 'Колонна из осквернённого камня',
 'block.malum.tainted_rock_column_cap': 'Навершие колонны из осквернённого камня',
 'block.malum.twisted_rock_column': 'Колонна из искажённого камня',
 'block.malum.twisted_rock_column_cap': 'Навершие колонны из искажённого камня',
 'block.malum.tainted_rock_slab': 'Плита из осквернённого камня',
 'block.malum.tainted_rock_stairs': 'Ступеньки из осквернённого камня',
 'block.malum.tainted_rock_wall': 'Ограда из осквернённого камня',
 'block.malum.tainted_rock_button': 'Кнопка из осквернённого камня',
 'block.malum.tainted_rock_pressure_plate': 'Нажимная плита из осквернённого камня',
 'block.malum.twisted_rock_slab': 'Плита из искажённого камня',
 'block.malum.twisted_rock_stairs': 'Ступеньки из искажённого камня',
 'block.malum.twisted_rock_wall': 'Ограда из искажённого камня',
 'block.malum.twisted_rock_button': 'Кнопка из искажённого камня',
 'block.malum.twisted_rock_pressure_plate': 'Нажимная плита из искажённого камня',
 # ---- рунические разновидности камня ----
 'block.malum.runic_tainted_rock_bricks': 'Рунические кирпичи из осквернённого камня',
 'block.malum.runic_tainted_rock_bricks_slab': 'Плита из рунических кирпичей осквернённого камня',
 'block.malum.runic_tainted_rock_bricks_stairs': 'Ступеньки из рунических кирпичей осквернённого камня',
 'block.malum.runic_tainted_rock_bricks_wall': 'Ограда из рунических кирпичей осквернённого камня',
 'block.malum.runic_twisted_rock_bricks': 'Рунические кирпичи из искажённого камня',
 'block.malum.runic_twisted_rock_bricks_slab': 'Плита из рунических кирпичей искажённого камня',
 'block.malum.runic_twisted_rock_bricks_stairs': 'Ступеньки из рунических кирпичей искажённого камня',
 'block.malum.runic_twisted_rock_bricks_wall': 'Ограда из рунических кирпичей искажённого камня',
 'block.malum.runic_small_tainted_rock_bricks': 'Рунические мелкие кирпичи из осквернённого камня',
 'block.malum.runic_small_tainted_rock_bricks_slab': 'Плита из рунических мелких кирпичей осквернённого камня',
 'block.malum.runic_small_tainted_rock_bricks_stairs': 'Ступеньки из рунических мелких кирпичей осквернённого камня',
 'block.malum.runic_small_tainted_rock_bricks_wall': 'Ограда из рунических мелких кирпичей осквернённого камня',
 'block.malum.runic_small_twisted_rock_bricks': 'Рунические мелкие кирпичи из искажённого камня',
 'block.malum.runic_small_twisted_rock_bricks_slab': 'Плита из рунических мелких кирпичей искажённого камня',
 'block.malum.runic_small_twisted_rock_bricks_stairs': 'Ступеньки из рунических мелких кирпичей искажённого камня',
 'block.malum.runic_small_twisted_rock_bricks_wall': 'Ограда из рунических мелких кирпичей искажённого камня',
 'block.malum.runic_tainted_rock_tiles': 'Рунический плитняк из осквернённого камня',
 'block.malum.runic_tainted_rock_tiles_slab': 'Плита из рунического плитняка осквернённого камня',
 'block.malum.runic_tainted_rock_tiles_stairs': 'Ступеньки из рунического плитняка осквернённого камня',
 'block.malum.runic_tainted_rock_tiles_wall': 'Ограда из рунического плитняка осквернённого камня',
 'block.malum.runic_twisted_rock_tiles': 'Рунический плитняк из искажённого камня',
 'block.malum.runic_twisted_rock_tiles_slab': 'Плита из рунического плитняка искажённого камня',
 'block.malum.runic_twisted_rock_tiles_stairs': 'Ступеньки из рунического плитняка искажённого камня',
 'block.malum.runic_twisted_rock_tiles_wall': 'Ограда из рунического плитняка искажённого камня',
 # ---- рунное дерево ----
 'block.malum.runewood': 'Рунная древесина',
 'block.malum.runewood_log': 'Бревно рунного дерева',
 'block.malum.stripped_runewood': 'Обтёсанная рунная древесина',
 'block.malum.stripped_runewood_log': 'Обтёсанное бревно рунного дерева',
 'block.malum.exposed_runewood_log': 'Обнажённое бревно рунного дерева',
 'block.malum.revealed_runewood_log': 'Проявленное бревно рунного дерева',
 'block.malum.runewood_leaves': 'Листва рунного дерева',
 'block.malum.hanging_runewood_leaves': 'Свисающая листва рунного дерева',
 'block.malum.azure_runewood_leaves': 'Лазурная листва рунного дерева',
 'block.malum.hanging_azure_runewood_leaves': 'Свисающая лазурная листва рунного дерева',
 'block.malum.runewood_sapling': 'Саженец рунного дерева',
 'block.malum.azure_runewood_sapling': 'Лазурный саженец рунного дерева',
 'block.malum.runewood_planks': 'Доски рунного дерева',
 'block.malum.runewood_planks_slab': 'Плита из рунного дерева',
 'block.malum.runewood_planks_stairs': 'Ступеньки из рунного дерева',
 'block.malum.runewood_planks_button': 'Кнопка из рунного дерева',
 'block.malum.runewood_planks_fence': 'Забор из рунного дерева',
 'block.malum.runewood_planks_fence_gate': 'Калитка из рунного дерева',
 'block.malum.runewood_planks_pressure_plate': 'Нажимная плита из рунного дерева',
 'block.malum.cut_runewood_planks': 'Струганные доски рунного дерева',
 'block.malum.rustic_runewood_planks': 'Грубые доски рунного дерева',
 'block.malum.rustic_runewood_planks_slab': 'Плита из грубых досок рунного дерева',
 'block.malum.rustic_runewood_planks_stairs': 'Ступеньки из грубых досок рунного дерева',
 'block.malum.vertical_runewood_planks': 'Вертикальные доски рунного дерева',
 'block.malum.vertical_runewood_planks_slab': 'Плита из вертикальных досок рунного дерева',
 'block.malum.vertical_runewood_planks_stairs': 'Ступеньки из вертикальных досок рунного дерева',
 'block.malum.vertical_rustic_runewood_planks': 'Вертикальные грубые доски рунного дерева',
 'block.malum.vertical_rustic_runewood_planks_slab': 'Плита из вертикальных грубых досок рунного дерева',
 'block.malum.vertical_rustic_runewood_planks_stairs': 'Ступеньки из вертикальных грубых досок рунного дерева',
 'block.malum.rustic_runewood_tiles': 'Грубая плитка из рунного дерева',
 'block.malum.rustic_runewood_tiles_slab': 'Плита из грубой плитки рунного дерева',
 'block.malum.rustic_runewood_tiles_stairs': 'Ступеньки из грубой плитки рунного дерева',
 'block.malum.runewood_tiles': 'Плитка из рунного дерева',
 'block.malum.runewood_tiles_slab': 'Плита из плитки рунного дерева',
 'block.malum.runewood_tiles_stairs': 'Ступеньки из плитки рунного дерева',
 'block.malum.runewood_boards': 'Обшивка из рунного дерева',
 'block.malum.runewood_boards_slab': 'Плита из обшивки рунного дерева',
 'block.malum.runewood_boards_stairs': 'Ступеньки из обшивки рунного дерева',
 'block.malum.runewood_boards_wall': 'Ограда из обшивки рунного дерева',
 'block.malum.runewood_boards_door': 'Дверь из обшивки рунного дерева',
 'block.malum.runewood_boards_trapdoor': 'Люк из обшивки рунного дерева',
 'block.malum.vertical_runewood_boards': 'Вертикальная обшивка из рунного дерева',
 'block.malum.vertical_runewood_boards_slab': 'Плита из вертикальной обшивки рунного дерева',
 'block.malum.vertical_runewood_boards_stairs': 'Ступеньки из вертикальной обшивки рунного дерева',
 'block.malum.runewood_beam': 'Балка из рунного дерева',
 'block.malum.runewood_panel': 'Панель из рунного дерева',
 'block.malum.runewood_door': 'Дверь из рунного дерева',
 'block.malum.runewood_trapdoor': 'Люк из рунного дерева',
 'block.malum.runewood_sign': 'Табличка из рунного дерева',
 'block.malum.bolted_runewood_door': 'Укреплённая дверь из рунного дерева',
 'block.malum.bolted_runewood_trapdoor': 'Укреплённый люк из рунного дерева',
 'block.malum.bolted_runewood_boards_door': 'Укреплённая дверь из обшивки рунного дерева',
 'block.malum.bolted_runewood_boards_trapdoor': 'Укреплённый люк из обшивки рунного дерева',
 'block.malum.runewood_totem_base': 'Основание тотема из рунного дерева',
 'block.malum.runewood_totem_pole': 'Столб тотема из рунного дерева',
 'block.malum.waveform_runewood_totem_base': 'Волновое основание тотема из рунного дерева',
 # ---- дерево душ ----
 'block.malum.soulwood': 'Древесина души',
 'block.malum.soulwood_log': 'Бревно дерева души',
 'block.malum.stripped_soulwood': 'Обтёсанная древесина души',
 'block.malum.stripped_soulwood_log': 'Обтёсанное бревно дерева души',
 'block.malum.exposed_soulwood_log': 'Обнажённое бревно дерева души',
 'block.malum.revealed_soulwood_log': 'Проявленное бревно дерева души',
 'block.malum.soulwood_leaves': 'Листва дерева души',
 'block.malum.hanging_soulwood_leaves': 'Свисающая листва дерева души',
 'block.malum.soulwood_sapling': 'Саженец дерева души',
 'block.malum.soulwood_planks': 'Доски из дерева души',
 'block.malum.soulwood_planks_slab': 'Плита из дерева души',
 'block.malum.soulwood_planks_stairs': 'Ступеньки из дерева души',
 'block.malum.soulwood_planks_button': 'Кнопка из дерева души',
 'block.malum.soulwood_planks_fence': 'Забор из дерева души',
 'block.malum.soulwood_planks_fence_gate': 'Калитка из досок дерева души',
 'block.malum.soulwood_planks_pressure_plate': 'Нажимная плита из дерева души',
 'block.malum.cut_soulwood_planks': 'Струганные доски дерева души',
 'block.malum.rustic_soulwood_planks': 'Грубые доски дерева души',
 'block.malum.rustic_soulwood_planks_slab': 'Плита из грубых досок дерева души',
 'block.malum.rustic_soulwood_planks_stairs': 'Ступеньки из грубых досок дерева души',
 'block.malum.vertical_soulwood_planks': 'Вертикальные доски дерева души',
 'block.malum.vertical_soulwood_planks_slab': 'Плита из вертикальных досок дерева души',
 'block.malum.vertical_soulwood_planks_stairs': 'Ступеньки из вертикальных досок дерева души',
 'block.malum.vertical_rustic_soulwood_planks': 'Вертикальные грубые доски дерева души',
 'block.malum.vertical_rustic_soulwood_planks_slab': 'Плита из вертикальных грубых досок дерева души',
 'block.malum.vertical_rustic_soulwood_planks_stairs': 'Ступеньки из вертикальных грубых досок дерева души',
 'block.malum.rustic_soulwood_tiles': 'Грубая плитка из дерева души',
 'block.malum.rustic_soulwood_tiles_slab': 'Плита из грубой плитки дерева души',
 'block.malum.rustic_soulwood_tiles_stairs': 'Ступеньки из грубой плитки дерева души',
 'block.malum.soulwood_tiles': 'Плитка из дерева души',
 'block.malum.soulwood_tiles_slab': 'Плита из плитки дерева души',
 'block.malum.soulwood_tiles_stairs': 'Ступеньки из плитки дерева души',
 'block.malum.soulwood_boards': 'Обшивка из дерева души',
 'block.malum.soulwood_boards_slab': 'Плита из обшивки дерева души',
 'block.malum.soulwood_boards_stairs': 'Ступеньки из обшивки дерева души',
 'block.malum.soulwood_boards_wall': 'Ограда из обшивки дерева души',
 'block.malum.soulwood_boards_door': 'Дверь из обшивки дерева души',
 'block.malum.soulwood_boards_trapdoor': 'Люк из обшивки дерева души',
 'block.malum.vertical_soulwood_boards': 'Вертикальная обшивка из дерева души',
 'block.malum.vertical_soulwood_boards_slab': 'Плита из вертикальной обшивки дерева души',
 'block.malum.vertical_soulwood_boards_stairs': 'Ступеньки из вертикальной обшивки дерева души',
 'block.malum.soulwood_beam': 'Балка из дерева души',
 'block.malum.soulwood_panel': 'Панель из дерева души',
 'block.malum.soulwood_door': 'Дверь из дерева души',
 'block.malum.soulwood_trapdoor': 'Люк из дерева души',
 'block.malum.soulwood_sign': 'Табличка из дерева души',
 'block.malum.bolted_soulwood_door': 'Укреплённая дверь из дерева души',
 'block.malum.bolted_soulwood_trapdoor': 'Укреплённый люк из дерева души',
 'block.malum.bolted_soulwood_boards_door': 'Укреплённая дверь из обшивки дерева души',
 'block.malum.bolted_soulwood_boards_trapdoor': 'Укреплённый люк из обшивки дерева души',
 'block.malum.soulwood_totem_base': 'Основание тотема из дерева души',
 'block.malum.soulwood_totem_pole': 'Столб тотема из дерева души',
 'block.malum.waveform_soulwood_totem_base': 'Волновое основание тотема из дерева души',
 'block.malum.soulwoven_banner': 'Знамя, сотканное из душ',
 # ---- Плачущий колодец ----
 'block.malum.primordial_soup': 'Плачущий колодец',
 'block.malum.void_conduit': 'Плачущий колодец',
 'block.malum.weeping_well_center': 'Центр плачущего колодца',
 'block.malum.weeping_well_column': 'Колонна плачущего колодца',
 'block.malum.weeping_well_column_base': 'Основание колонны плачущего колодца',
 'block.malum.weeping_well_column_cap': 'Навершие колонны плачущего колодца',
 'block.malum.weeping_well_corner': 'Угол плачущего колодца',
 'block.malum.weeping_well_flagstone': 'Плитняк плачущего колодца',
 'block.malum.weeping_well_side': 'Боковая сторона плачущего колодца',
 'block.malum.weeping_well_side_mirror': 'Зеркальная боковая сторона плачущего колодца',
 # ---- устройства и прочее ----
 'block.malum.the_device': 'Устройство',
 'block.malum.the_vessel': 'Сосуд',
 'block.malum.void_depot': 'Пустотное хранилище',
 'block.malum.gust_igniter': 'Зажигатель порывов',
 'block.malum.wind_tunnel': 'Ветряной тоннель',
 'block.malum.wavebanker': 'Волнонакопитель',
 'block.malum.wavebreaker': 'Волнопрерыватель',
 'block.malum.wavecharger': 'Волнозарядчик',
 'block.malum.wavemaker': 'Волнообразователь',
}
