# -*- coding: utf-8 -*-
# Malum, часть 3б: сущности, интеграция с Tetra, вымпелы, устройства, JEI, песни.
P3B = {
 # ---- сущности ----
 'entity.malum.ascending_block': 'Восходящий блок',
 'entity.malum.bound_rite_locus': 'Связанный очаг ритуала',
 'entity.malum.draining_bolt': 'Иссушающий снаряд',
 'entity.malum.entropic_flame_bolt': 'Энтропийный огненный снаряд',
 'entity.malum.etheric_nitrate': 'Эфирный нитрат',
 'entity.malum.hex_bolt': 'Колдовской снаряд',
 'entity.malum.hidden_blade_delayed_impact': 'Отложенный удар скрытого клинка',
 'entity.malum.natural_spirit': 'Природный дух',
 'entity.malum.pneuma_void': 'Пневматическая пустота',
 'entity.malum.scythe_boomerang': 'Коса-бумеранг',
 'entity.malum.scythe_maelstrom': 'Водоворот косы',
 'entity.malum.seeking_rite_locus': 'Ищущий очаг ритуала',
 'entity.malum.spellweavers_locus': 'Очаг плетения заклинаний',
 'entity.malum.sundering_anchor': 'Сокрушающий якорь',
 'entity.malum.thrown_gluttony': 'Брошенное чревоугодие',
 'entity.malum.vivid_nitrate': 'Яркий нитрат',
 # ---- интеграция с Tetra ----
 'tetra.improvement.malum.soul_strike.name': 'Удар по душе',
 'tetra.improvement.malum.soul_strike.description': 'Материал предмета позволяет ему бить по душе.',
 'tetra.material.hallowed_gold': 'Священное золото',
 'tetra.material.hallowed_gold.prefix': 'Священное золото',
 'tetra.material.malignant_pewter': 'Злокачественный пьютер',
 'tetra.material.malignant_pewter.prefix': 'Злокачественный пьютер',
 'tetra.material.runewood': 'Рунное дерево',
 'tetra.material.runewood.prefix': 'Рунное дерево',
 'tetra.material.soul_stained_steel': 'Духосталь',
 'tetra.material.soul_stained_steel.prefix': 'Духосталь',
 'tetra.material.soulwood': 'Дерево душ',
 'tetra.material.soulwood.prefix': 'Дерево душ',
 'tetra.material.soulwoven_silk': 'Шёлк, сотканный из душ',
 'tetra.material.soulwoven_silk.prefix': 'Шёлк, сотканный из душ',
 'tetra.material.tainted_rock': 'Осквернённый камень',
 'tetra.material.tainted_rock.prefix': 'Осквернённый камень',
 'tetra.material.twisted_rock': 'Искажённый камень',
 'tetra.material.twisted_rock.prefix': 'Искажённый камень',
 # ---- вымпелы ----
 'banner_pattern.malum.break': 'Разлом',
 'banner_pattern.malum.breath': 'Дыхание',
 'banner_pattern.malum.breeze': 'Ветерок',
 'banner_pattern.malum.burn': 'Ожог',
 'banner_pattern.malum.colorful_world': 'Цветной мир',
 'banner_pattern.malum.default': 'По умолчанию',
 'banner_pattern.malum.hallucination': 'Галлюцинация',
 'banner_pattern.malum.heft': 'Тяжесть',
 'banner_pattern.malum.horns': 'Рога',
 'banner_pattern.malum.hunger': 'Голод',
 'banner_pattern.malum.sanity': 'Здравомыслие',
 'banner_pattern.malum.sequence': 'Последовательность',
 'banner_pattern.malum.spawn': 'Зарождение',
 'banner_pattern.malum.sword': 'Меч',
 # ---- волновые устройства ----
 'malum.waveform_artifice.guide.0': 'Отпустите ПКМ, чтобы подтвердить',
 'malum.waveform_artifice.guide.1': 'ЛКМ меняет единицу измерения',
 'malum.waveform_artifice.guide.2': 'Колесо мыши — точная настройка значения',
 'malum.waveform_artifice.gust_igniter': 'Сила порыва',
 'malum.waveform_artifice.gust_igniter.alt': 'Поднимающий порыв',
 'malum.waveform_artifice.gust_igniter.default': 'Восходящий порыв',
 'malum.waveform_artifice.minute': 'минута',
 'malum.waveform_artifice.minute_plural': 'минуты',
 'malum.waveform_artifice.redstone_tick': 'тик редстоуна',
 'malum.waveform_artifice.redstone_tick_plural': 'тики редстоуна',
 'malum.waveform_artifice.second': 'секунда',
 'malum.waveform_artifice.second_plural': 'секунды',
 'malum.waveform_artifice.value_display': ': %1$s %2$s',
 'malum.waveform_artifice.wavebanker': 'Длительность импульса редстоуна',
 'malum.waveform_artifice.wavebreaker': 'Задержка импульса редстоуна',
 'malum.waveform_artifice.wavecharger': 'Длительность шага редстоуна',
 'malum.waveform_artifice.wavemaker': 'Интервал импульсов редстоуна',
 'malum.waveform_artifice.wind_tunnel': 'Длина тоннеля',
 'malum.waveform_artifice.wind_tunnel.alt': 'Внутренний поток',
 'malum.waveform_artifice.wind_tunnel.default': 'Наружный поток',
 # ---- духи в интерфейсе ----
 'malum.spirit.description.stored_soul': 'Хранит душу с:  ',
 'malum.spirit.description.stored_spirit': 'Содержит:  ',
 # ---- музыка ----
 'jukebox_song.malum.aesthetica': 'Kultik - Aesthetica',
 'jukebox_song.malum.arcane_elegy': 'Kultik - Arcane Elegy',
 # ---- JEI ----
 'malum.jei.runeworking': 'Создание рун',
 'malum.jei.spirit_focusing': 'Фокусировка духов',
 'malum.jei.spirit_infusion': 'Насыщение духами',
 'malum.jei.spirit_repair': 'Починка духами',
 'malum.jei.spirit_rite': 'Ритуалы духов',
 'malum.jei.spirit_transmutation': 'Освобождённый ритуал',
 'malum.jei.weeping_well': 'Плачущий колодец',
}
