# -*- coding: utf-8 -*-
# Malum, часть 4б: геасы — названия, «за» и «против», реплики.
P4B = {
 'malum.gui.geas.type': 'Геас',
 'malum.gui.geas.sworn': 'Когда принят: ',
 'malum.gui.geas.creative': 'Творческий предмет для отладки.',
 'malum.gui.geas.creative_help': 'Используйте, чтобы принять или нарушить эффект геаса.',
 # ---- Власти ----
 'malum.gui.geas.authority_of_the_gleeful_target': 'Власть радостной мишени',
 'malum.gui.geas.authority_of_the_gleeful_target.cons': '$m0.8/$Ваше тело застыло во времени, аномалия, отрешённая от этого мира. Оно не стареет и не чувствует.\n-Всё входящее исцеление делится на четыре',
 'malum.gui.geas.authority_of_the_gleeful_target.pros': '$m0.55/$Власть — договор между вашей душой и самим миром.\n-Ваше тело окутано спящим стазисом. При каждом ударе стазис активируется\n-Пока действует стазис, все эффекты зелий замирают и не могут истечь\n-Эффекты вроде регенерации или яда, которым нужно течение времени, перестают действовать, а блага, безразличные к стазису, остаются',
 'malum.gui.geas.authority_of_the_gleeful_target.tooltip': 'Бери всё, пусть это не прекращается, ещё, ещё и ещё',
 'malum.gui.geas.authority_of_the_inverted_heart': 'Власть обращённого сердца',
 'malum.gui.geas.authority_of_the_inverted_heart.cons': '$m0.8/$Ваша душа — душа мира. Ваше сердце — сердце мира. Оно открыто, открыто для всех, уязвимо для каждого.\n-Учетверяет входящий магический урон',
 'malum.gui.geas.authority_of_the_inverted_heart.pros': '$m0.7/$Власть — договор между вашей душой и самим миром.\n-Ваша душа открывается миру вокруг. Когда её видит другая душа, между вами возникает связь\n-Связанные цели получают любой урон, который вы наносите или получаете',
 'malum.gui.geas.authority_of_the_inverted_heart.tooltip': 'Твоё сердце — мир, и мир бьётся',
 # ---- Символ ----
 'malum.gui.geas.creed_of_the_blight_eater': 'Кредо пожирателя порчи',
 'malum.gui.geas.creed_of_the_blight_eater.tooltip': 'Мммм… порча… такая вкусная…',
 # ---- Клятвы ----
 'malum.gui.geas.oath_of_the_overburdened_mind': 'Клятва обременённого разума',
 'malum.gui.geas.oath_of_the_overburdened_mind.cons': 'Вложенное понимание требует осмотрительности\n -Длительность зарядки посоха увеличивается на одну четверть',
 'malum.gui.geas.oath_of_the_overburdened_mind.pros': 'Вместимость арканного знания, вложенного в разум\n-Удваивает ёмкость зарядов посоха',
 'malum.gui.geas.oath_of_the_overburdened_mind.tooltip': 'Семь раз отмерь, один раз отрежь',
 'malum.gui.geas.oath_of_the_overeager_fist': 'Клятва слишком рьяного кулака',
 'malum.gui.geas.oath_of_the_overeager_fist.cons': 'Вложенное рвение требует немедленных действий\n -Заряды посоха выстреливают сразу же по завершении зарядки',
 'malum.gui.geas.oath_of_the_overeager_fist.pros': 'Рвение, вложенное в тело и душу\n-Длительность зарядки посоха сокращается вдвое',
 'malum.gui.geas.oath_of_the_overeager_fist.tooltip': 'Режь дважды, не меряй ни разу',
 'malum.gui.geas.oath_of_the_overkeen_eye': 'Клятва слишком зоркого глаза',
 'malum.gui.geas.oath_of_the_overkeen_eye.cons': 'Вложенная осведомлённость требует двойной подготовки\n -Скорость восстановления зарядов посоха снижается вдвое',
 'malum.gui.geas.oath_of_the_overkeen_eye.pros': 'Зоркий глаз на аркану, вложенный в душу\n-Снаряды посоха получают самонаведение',
 'malum.gui.geas.oath_of_the_overkeen_eye.tooltip': 'Дважды отмерь, один раз отрежь',
 'malum.gui.geas.oath_of_the_undiscerned_maw': 'Клятва неразличимой утробы',
 'malum.gui.geas.oath_of_the_undiscerned_maw.cons': 'Рождённая из злокачественности, поглощённая сущность несёт в себе волю к разрушению\n-Чрезмерное использование эффекта исцеления постепенно ослабляет всё входящее исцеление',
 'malum.gui.geas.oath_of_the_undiscerned_maw.pros': '$m0.8/$Гравировка, наложенная на злокачественное избавление\n-Злокачественные критические удары пожирают жизненную сущность поражённых существ\n-Поглощённая сущность исцеляет вас пропорционально нанесённому урону',
 'malum.gui.geas.oath_of_the_undiscerned_maw.tooltip': 'Забирай жизнь своих врагов',
 'malum.gui.geas.oath_of_unmakers_disdain': 'Клятва презрения разрушителя',
 'malum.gui.geas.oath_of_unmakers_disdain.cons': 'В симбиозе со злокачественной эгидой клятва высасывает её силу\n-Снижает ёмкость злокачественной эгиды',
 'malum.gui.geas.oath_of_unmakers_disdain.pros': '$m0.75/$Гравировка, наложенная на злокачественное избавление\n-Злокачественные критические удары раз за разом полосуют цели\n-Дополнительные удары растут в силе и количестве за счёт злокачественного преобразования',
 'malum.gui.geas.oath_of_unmakers_disdain.tooltip': 'Не признавай никого и не будь признан никем',
 'malum.gui.geas.oath_of_unsighted_resistance': 'Клятва незрячего сопротивления',
 'malum.gui.geas.oath_of_unsighted_resistance.cons': '$m0.8/$Дар клятвы притупляет силу злокачественных ударов\n-Снижает урон злокачественных критических ударов при перезарядке злокачественной эгиды',
 'malum.gui.geas.oath_of_unsighted_resistance.pros': 'Гравировка, наложенная на злокачественное избавление\n-Злокачественные критические удары перезаряжают злокачественную эгиду',
 'malum.gui.geas.oath_of_unsighted_resistance.tooltip': 'Не вижу зла, не чувствую зла',
 # ---- Пакты ----
 'malum.gui.geas.pact_of_combustion': 'Пакт горения',
 'malum.gui.geas.pact_of_combustion.cons': 'Вы не можете отнять у пламени его природу\n -Насильственное тушение разит вас инфернальной арканой',
 'malum.gui.geas.pact_of_combustion.pros': 'Нет силы могущественнее.\n -Наложенные вами на врагов эффекты горения усиливаются',
 'malum.gui.geas.pact_of_combustion.tooltip': 'Поджигать и смотреть',
 'malum.gui.geas.pact_of_contentedness': 'Пакт довольства',
 'malum.gui.geas.pact_of_contentedness.cons': 'Быть довольным — значит жить в достатке\n -Броня и прочность брони снижаются вдвое при голоде, близком к истощению',
 'malum.gui.geas.pact_of_contentedness.pros': 'Быть цельным — значит быть довольным.\n -Броня и прочность брони увеличиваются на одну пятую при насыщении',
 'malum.gui.geas.pact_of_contentedness.tooltip': 'Быть сытым — значит стоять на якоре',
 'malum.gui.geas.pact_of_defiance': 'Пакт непокорности',
 'malum.gui.geas.pact_of_defiance.cons': 'Магия меняет ваше восприятие смерти: каждое очко урона становится значимее.\n -Снижает максимальное здоровье на одну пятую',
 'malum.gui.geas.pact_of_defiance.pros': '$m0.8/$Противоестественная регенерация, вложенная в тело, — желание расти вечно.\n -Насыщение исцеляет вдвое быстрее, втрое быстрее — на краю гибели\n -Увеличивает получаемое исцеление на четыре десятых',
 'malum.gui.geas.pact_of_defiance.tooltip': 'Бушуй, бушуй против угасания своей мощи',
 'malum.gui.geas.pact_of_patience_repaid': 'Пакт возданного терпения',
 'malum.gui.geas.pact_of_patience_repaid.cons': 'Затянувшаяся боль — боль бо́льшая.\n -Буферизованный урон наносится как магический и в целом на одну пятую сильнее',
 'malum.gui.geas.pact_of_patience_repaid.pros': '$m0.8/$Раздели удар, смягчи последствия.\n -Половина всего входящего урона буферизуется, превращаясь в урон со временем\n -Буферизованный урон не может убить вас',
 'malum.gui.geas.pact_of_patience_repaid.tooltip': 'Искажённое эхо',
 'malum.gui.geas.pact_of_reciprocation': 'Пакт взаимности',
 'malum.gui.geas.pact_of_reciprocation.cons': 'Война — это всё, что вы есть.\n -Отключает естественное восстановление оберега души',
 'malum.gui.geas.pact_of_reciprocation.pros': 'Перемена, новый главенствующий механизм.\n -Нанесение магического урона восполняет оберег души\n -Значительно увеличивает ёмкость оберега души\n -Удваивает прирост оберега души',
 'malum.gui.geas.pact_of_reciprocation.tooltip': 'Докажи свою силу, владея ею',
 'malum.gui.geas.pact_of_rune_exploitation': 'Пакт использования рун',
 'malum.gui.geas.pact_of_rune_exploitation.cons': '$m0.8/$Ваша душа выдержит лишь столько-то\n -Каждая надетая руна снижает получаемое исцеление, броню, прочность брони и сопротивление магии на одну двадцатую',
 'malum.gui.geas.pact_of_rune_exploitation.pros': 'Часть вашей души становится вместилищем для рун.\n -Дарует два слота рун',
 'malum.gui.geas.pact_of_rune_exploitation.tooltip': 'Собери их все, исчерпай все возможности',
 'malum.gui.geas.pact_of_self_care': 'Пакт заботы о себе',
 'malum.gui.geas.pact_of_self_care.cons': 'Голодать — значит полностью потерять себя.\n -При низком голоде здоровье убывает гораздо быстрее',
 'malum.gui.geas.pact_of_self_care.pros': 'Наслаждайся усладой и очищай свою душу.\n -Еда даёт больше насыщения\n -Еда снимает отрицательные эффекты',
 'malum.gui.geas.pact_of_self_care.tooltip': 'Ешь, иначе тело пожрёт само себя',
 'malum.gui.geas.pact_of_the_arcanaphage': 'Пакт арканофага',
 'malum.gui.geas.pact_of_the_arcanaphage.cons': 'Душа остаётся внутри не просто так.\n -Весь входящий урон превращается в магический\n -Целостность оберега души снижается вдвое',
 'malum.gui.geas.pact_of_the_arcanaphage.pros': '$m0.75/$Часть вашей души вытягивается из тела и служит приманкой для арканы.\n -Раскалывание души приносит дополнительную аркану\n -Сбор духов помогает большинству магических атрибутов',
 'malum.gui.geas.pact_of_the_arcanaphage.tooltip': 'Ищи магию в любом виде',
 'malum.gui.geas.pact_of_the_berserker': 'Пакт берсерка',
 'malum.gui.geas.pact_of_the_berserker.cons': 'Причиняй боль себе, причиняй боль другим\n -Ярость со временем убывает\n -Весь входящий урон удваивается',
 'malum.gui.geas.pact_of_the_berserker.pros': '$m0.7/$Бесконечная ярость, постоянный гнев: ваша боль рождает ярость, а ярость — сила.\n -Получаемый урон превращается в ярость\n -Нанося урон, вы расходуете ярость, чтобы раз за разом разить врагов скверной арканой',
 'malum.gui.geas.pact_of_the_berserker.tooltip': 'Твоя боль — их боль',
 'malum.gui.geas.pact_of_the_blastweaver': 'Пакт ткача взрывов',
 'malum.gui.geas.pact_of_the_blastweaver.cons': 'Ваша алчность подставляет вас под ваши же рукотворные разрушения.\n -Алчность повышает входящий урон от взрывов',
 'malum.gui.geas.pact_of_the_blastweaver.pros': '$m0.6/$Жадность и спешка, питаемые кинетическим ударом.\n -Взрывы значительно усиливаются и при детонации даруют алчность\n -Алчность повышает шанс удачи\n -Алчность дополнительно усиливает взрывы',
 'malum.gui.geas.pact_of_the_blastweaver.tooltip': 'Черпай силу в безрассудстве',
 'malum.gui.geas.pact_of_the_cloudskipper': 'Пакт скачущего по облакам',
 'malum.gui.geas.pact_of_the_cloudskipper.cons': 'То, на что вы полагаетесь, в итоге вас и раздавит.\n -Получаемый урон от падения удваивается',
 'malum.gui.geas.pact_of_the_cloudskipper.pros': '$m0.8/$Гравитация — величайшая сила, которую можно обратить себе на пользу.\n -Порывы ветра сильнее подбрасывают и даруют восхождение\n -Состояние восхождения улучшает маневренность в воздухе',
 'malum.gui.geas.pact_of_the_cloudskipper.tooltip': 'Танцуй на краю опасности',
 'malum.gui.geas.pact_of_the_continuing_shot': 'Пакт непрерывного выстрела',
 'malum.gui.geas.pact_of_the_continuing_shot.cons': 'Нельзя притвориться безупречным.\n -Промах снимает все бонусы к скорости натяжения и вместо этого ослабляет её',
 'malum.gui.geas.pact_of_the_continuing_shot.pros': 'Точность — залог успеха.\n -Урон из лука ускоряет натяжение для большинства дальнобойного оружия',
 'malum.gui.geas.pact_of_the_continuing_shot.tooltip': 'Шаг. Стойка. Готовность. Подъём. Начало. Натяжение. Выпуск.',
 'malum.gui.geas.pact_of_the_fortress': 'Пакт крепости',
 'malum.gui.geas.pact_of_the_fortress.cons': 'Добавленное величие несёт в себе вялость\n -Скорость восстановления оберега души снижается вдвое',
 'malum.gui.geas.pact_of_the_fortress.pros': 'Сжатие оберега души, ставшее больше и тоньше.\n -Увеличивает ёмкость оберега души\n -Увеличивает целостность оберега души наполовину',
 'malum.gui.geas.pact_of_the_fortress.tooltip': 'Будь силён, когда ты нужен',
 'malum.gui.geas.pact_of_the_high_priest': 'Пакт верховного жреца',
 'malum.gui.geas.pact_of_the_high_priest.cons': '$m0.8/$Ваша чрезмерно жадная хватка вредна.\n -Эффект радиуса уходит в откат при получении урона от врага\n -Состояние отката снижает скорость передвижения',
 'malum.gui.geas.pact_of_the_high_priest.pros': 'Весь мир — ваш.\n -Увеличивает радиус взаимодействия с блоками на одну пятую и радиус атаки по существам — на одну десятую',
 'malum.gui.geas.pact_of_the_high_priest.tooltip': 'Стань тем, во что они верят, пока они верят',
 'malum.gui.geas.pact_of_the_lifeweaver': 'Пакт ткача жизни',
 'malum.gui.geas.pact_of_the_lifeweaver.cons': 'Всякая тварь достойна заботы.\n -Аура исцеления действует на всех — и на союзников, и на врагов',
 'malum.gui.geas.pact_of_the_lifeweaver.pros': 'Редкая щедрость: всё, что вы есть, вы делите с другими.\n -Пассивно восстанавливает ваше здоровье\n -Восстановление здоровья делится с ближайшими существами',
 'malum.gui.geas.pact_of_the_lifeweaver.tooltip': 'Вплетай свою жизнь в чудеса',
 'malum.gui.geas.pact_of_the_lone_druid': 'Пакт одинокого друида',
 'malum.gui.geas.pact_of_the_lone_druid.cons': 'Быть свободным — значит сбросить все оковы\n -Любая надетая броня сковывает вас, раня вашу душу',
 'malum.gui.geas.pact_of_the_lone_druid.pros': '$m0.7/$Быть цельным — значит быть свободным.\n -Каждый пустой слот брони даёт пять единиц брони и две единицы прочности брони\n -Каждый пустой слот брони увеличивает получаемое исцеление на одну четверть',
 'malum.gui.geas.pact_of_the_lone_druid.tooltip': 'Сбрось свою вторую кожу',
 'malum.gui.geas.pact_of_the_parasite': 'Пакт паразита',
 'malum.gui.geas.pact_of_the_parasite.cons': 'Ваша хрупкость всё ещё вполне реальна.\n -Снижает получаемое исцеление на четыре десятых',
 'malum.gui.geas.pact_of_the_parasite.pros': 'Избыток уверенности, вложенный в разум: ваша боль лишь вторична.\n -Сбор духов даёт поглощение',
 'malum.gui.geas.pact_of_the_parasite.tooltip': 'Зачем трудиться ради того, что есть у других',
 'malum.gui.geas.pact_of_the_profane_ascetic': 'Пакт нечестивого аскета',
 'malum.gui.geas.pact_of_the_profane_ascetic.cons': 'Ваша преданность гниению дорого обходится телу.\n -Насыщение и голод больше не восстанавливают здоровье\n -Еда из отвергнутых продуктов несёт гибель',
 'malum.gui.geas.pact_of_the_profane_ascetic.pros': '$m0.65/$Гниение станет вашим лучшим другом.\n -Чревоугодие становится испытанием веры, увеличивая получаемое исцеление\n -Испытание веры длится значительно дольше и имеет повышенный предел силы\n -Поедание гнилой пищи исцеляет вас и снимает потребность в аппетите',
 'malum.gui.geas.pact_of_the_profane_ascetic.tooltip': 'Отвергни излишества и будь исцелён гниением',
 'malum.gui.geas.pact_of_the_profane_glutton': 'Пакт нечестивого чревоугодника',
 'malum.gui.geas.pact_of_the_profane_glutton.cons': '$m0.8/$Гниение поглотит вас.\n -Отчаянная нужда снижает броню и сопротивление магии\n -Урон от истощения отравляет вас\n -Отравленные враги передают яд вам',
 'malum.gui.geas.pact_of_the_profane_glutton.pros': '$m0.6/$Гниение станет вашим лучшим оружием.\n -Чревоугодие становится отчаянной нуждой, существенно повышая мастерство косы\n -Отчаянная нужда набирает силу быстрее и имеет повышенный предел силы\n -Удары косой под благословением отчаянной нужды создают дополнительный ядовитый разрез',
 'malum.gui.geas.pact_of_the_profane_glutton.tooltip': 'Поглощай.',
 'malum.gui.geas.pact_of_the_prospector': 'Пакт старателя',
 'malum.gui.geas.pact_of_the_prospector.cons': 'Пылай алчностью\n -Удар по вам, пока вы охвачены алчностью, обволакивает вас пламенем',
 'malum.gui.geas.pact_of_the_prospector.pros': 'Милость, рождённая из пламени.\n -Сбор драгоценных минералов дарует алчность\n -Алчность постепенно повышает шанс удачи\n -Алчность дополнительно восстанавливает одно сердце утраченного здоровья',
 'malum.gui.geas.pact_of_the_prospector.tooltip': 'Охвати себя алчностью',
 'malum.gui.geas.pact_of_the_reaper': 'Пакт жнеца',
 'malum.gui.geas.pact_of_the_reaper.cons': 'Разорвать связь — значит погубить себя\n -Снижает урон отвергнутого оружия на девять десятых\n -Отвергнутое оружие разрушается при использовании',
 'malum.gui.geas.pact_of_the_reaper.pros': 'Пакт, скованный между вашей душой и вашей косой: цепи арканы связывают вас вместе.\n -Атаки косой иногда вызывают дополнительные разрезы',
 'malum.gui.geas.pact_of_the_reaper.tooltip': 'Присягни на верность лезвию',
 'malum.gui.geas.pact_of_the_shattering_addict': 'Пакт зависимости от раскалывания',
 'malum.gui.geas.pact_of_the_shattering_addict.cons': 'Заклинание дорого вам обходится.\n -Каждый день без сбора духов накапливает ломку, всё сильнее истощая голод, пока ваша жажда не будет утолена.',
 'malum.gui.geas.pact_of_the_shattering_addict.pros': '$m0.8/$Заклинание, навязанное разуму. Неутолимая жажда арканы\n -Раскалывание души приносит больше арканы\n -Ещё больше арканы при цепных раскалываниях душ',
 'malum.gui.geas.pact_of_the_shattering_addict.tooltip': 'Бери, что хочешь, и не останавливайся',
 'malum.gui.geas.pact_of_the_shield': 'Пакт щита',
 'malum.gui.geas.pact_of_the_shield.cons': 'Добавленное ускорение несёт в себе хрупкость\n -Целостность оберега души снижается вдвое',
 'malum.gui.geas.pact_of_the_shield.pros': 'Ускорение оберега души, созданное, чтобы поспеть в нужный миг.\n -Увеличивает ёмкость оберега души\n -Удваивает скорость восстановления оберега души',
 'malum.gui.geas.pact_of_the_shield.tooltip': 'Всегда будь готов встать и сражаться',
 'malum.gui.geas.pact_of_the_skybreaker': 'Пакт разящего небеса',
 'malum.gui.geas.pact_of_the_skybreaker.cons': 'То, что вы обрушиваете на других, вернётся к вам вдвойне.\n -Входящее отбрасывание удваивается',
 'malum.gui.geas.pact_of_the_skybreaker.pros': '$m0.8/$Гравитация — величайшая сила, которую можно обрушить на других.\n -Получив урон от падения, вы автоматически бьёте ближайших существ\n -Нанося урон от падения, вы бьёте цель независимо от расстояния',
 'malum.gui.geas.pact_of_the_skybreaker.tooltip': 'Двигайся и будь движим',
 'malum.gui.geas.pact_of_the_warlock': 'Пакт колдуна',
 'malum.gui.geas.pact_of_the_warlock.cons': 'Чувствуй гнев, причиняй гнев\n -Враги замечают вас вдвое раньше',
 'malum.gui.geas.pact_of_the_warlock.pros': 'Пакт, созданный, чтобы вплести гнев в боль.\n -Первый удар по врагам разит их скверной арканой',
 'malum.gui.geas.pact_of_the_warlock.tooltip': 'Тки аркану',
 'malum.gui.geas.pact_of_the_windswept': 'Пакт овеянного ветром',
 'malum.gui.geas.pact_of_the_windswept.cons': 'Будь ведом ветром\n -Если перестать бежать, бонус быстро убывает\n -Высокий импульс усиливает получаемое отбрасывание',
 'malum.gui.geas.pact_of_the_windswept.pros': 'Двигайся вместе с ветром.\n -Непрерывный бег накапливает скорость передвижения',
 'malum.gui.geas.pact_of_the_windswept.tooltip': 'Беги, как ветер',
 'malum.gui.geas.pact_of_tidal_affinity': 'Пакт приливного родства',
 'malum.gui.geas.pact_of_tidal_affinity.cons': 'Цепи океана крепко сжимают ваше сердце.\n -Вы не можете исцеляться вне воды',
 'malum.gui.geas.pact_of_tidal_affinity.pros': '$m0.7/$Замкни себя в океане, запомни хоровую тягу кондуита.\n -Под водой повышает ловкость, скорость атаки, скорость добычи и сопротивление урону\n -Сила кондуита усиливает перечисленные эффекты и пассивно восстанавливает здоровье',
 'malum.gui.geas.pact_of_tidal_affinity.tooltip': 'Стань воплощением океана',
 'malum.gui.geas.pact_of_wyrd_reconstruction': 'Пакт восстановления вирдом',
 'malum.gui.geas.pact_of_wyrd_reconstruction.cons': '$m0.8/$Горящие звёзды истощают вас.\n -Эффект восстановления несёт долгий откат\n -В состоянии отката арканный резонанс снижается вдвое\n -Сбор духов истощает голод',
 'malum.gui.geas.pact_of_wyrd_reconstruction.pros': '$m0.8/$Необузданная сила, взятая из самой смерти.\n -Смерть предотвращается восстановлением\n -Восстановление сопровождается краткой неуязвимостью и быстрым срабатыванием эффектов сбора духов',
 'malum.gui.geas.pact_of_wyrd_reconstruction.tooltip': 'Узри забвение и выкуй себя заново',
}
