# -*- coding: utf-8 -*-
# Malum, часть 3а: атрибуты, сообщения о смерти, эффекты, зачарования.
P3A = {
 # ---- атрибуты ----
 'attribute.name.malum.arcane_resonance': 'Арканный резонанс',
 'attribute.name.malum.arcane_resonance.desc': 'Бонус к силе эффектов сбора духов',
 'attribute.name.malum.charge_capacity': 'Ёмкость зарядов',
 'attribute.name.malum.charge_capacity.desc': 'Вместимость зарядов заклинаний',
 'attribute.name.malum.charge_duration': 'Длительность зарядки',
 'attribute.name.malum.charge_duration.desc': 'Длительность зарядки посоха',
 'attribute.name.malum.charge_recovery_rate': 'Скорость восстановления зарядов',
 'attribute.name.malum.charge_recovery_rate.desc': 'Процентное увеличение скорости восстановления зарядов заклинаний',
 'attribute.name.malum.geas_limit': 'Предел геаса',
 'attribute.name.malum.geas_limit.desc': 'Предел числа уз геаса, которые можно принять одновременно',
 'attribute.name.malum.healing_received': 'Получаемое исцеление',
 'attribute.name.malum.healing_received.desc': 'Увеличение получаемого исцеления',
 'attribute.name.malum.malignant_aegis_capacity': 'Ёмкость злокачественной эгиды',
 'attribute.name.malum.malignant_aegis_capacity.desc': 'Сильный многоцелевой атрибут сопротивления урону, даруемый злокачественной эгидой',
 'attribute.name.malum.malignant_aegis_recovery_gain': 'Прирост восстановления злокачественной эгиды',
 'attribute.name.malum.malignant_aegis_recovery_rate': 'Скорость восстановления злокачественной эгиды',
 'attribute.name.malum.malignant_conversion': 'Злокачественное преобразование',
 'attribute.name.malum.malignant_conversion.desc': 'Процент преобразования некоторых магических атрибутов в злокачественную эгиду',
 'attribute.name.malum.scythe_proficiency': 'Мастерство косы',
 'attribute.name.malum.scythe_proficiency.desc': 'Множитель урона кос',
 'attribute.name.malum.soul_ward_capacity': 'Ёмкость оберега души',
 'attribute.name.malum.soul_ward_capacity.desc': 'Вместимость оберега души',
 'attribute.name.malum.soul_ward_integrity': 'Целостность оберега души',
 'attribute.name.malum.soul_ward_integrity.desc': 'Процентное увеличение прочности оберега души',
 'attribute.name.malum.soul_ward_recovery_gain': 'Прирост восстановления оберега души',
 'attribute.name.malum.soul_ward_recovery_gain.desc': 'Процентное увеличение количества восстанавливаемого оберега души',
 'attribute.name.malum.soul_ward_recovery_rate': 'Скорость восстановления оберега души',
 'attribute.name.malum.soul_ward_recovery_rate.desc': 'Процентное увеличение скорости восстановления оберега души',
 'attribute.name.malum.spirit_spoils': 'Добыча духов',
 'attribute.name.malum.spirit_spoils.desc': 'Фиксированный прирост числа духов, добываемых с убитых врагов',
 # ---- сообщения о смерти ----
 'death.attack.berserker_spirit_impact': 'душа %1$s расколота %2$s',
 'death.attack.berserker_spirit_impact.item': 'душа %1$s расколота %2$s при помощи %3$s',
 'death.attack.hidden_blade_magic_counter': 'душа %1$s расколота на бесчисленные осколки %2$s',
 'death.attack.hidden_blade_magic_counter.item': 'душа %1$s расколота на бесчисленные осколки %2$s при помощи %3$s',
 'death.attack.hidden_blade_physical_counter': '%1$s был разрезан на бесчисленные куски %2$s',
 'death.attack.hidden_blade_physical_counter.item': '%1$s был разрезан на бесчисленные куски %2$s при помощи %3$s',
 'death.attack.inverted_heart_propagation': '%1$s попал в кармический поток %2$s',
 'death.attack.inverted_heart_propagation.item': '%1$s попал в кармический поток %2$s при помощи %3$s',
 'death.attack.inverted_heart_retaliation': '%1$s попал в кармический поток %2$s',
 'death.attack.inverted_heart_retaliation.item': '%1$s попал в кармический поток %2$s при помощи %3$s',
 'death.attack.karmic': '%1$s отрёкся от клятвы',
 'death.attack.karmic.player': '%1$s отрёкся от клятвы, пытаясь сбежать от %2$s',
 'death.attack.nitrate': 'душа %1$s была подорвана %2$s',
 'death.attack.nitrate.item': 'душа %1$s была подорвана %2$s при помощи %3$s',
 'death.attack.nitrate_playerless': 'душа %1$s была подорвана',
 'death.attack.nitrate_playerless.player': 'душа %1$s была подорвана при попытке сбежать от %2$s',
 'death.attack.rot': '%1$s был поглощён гниением',
 'death.attack.rot.player': '%1$s был поглощён гниением при попытке сбежать от %2$s',
 'death.attack.scythe_ascension': '%1$s был разрублен приёмом «Восхождение» %2$s',
 'death.attack.scythe_ascension.item': '%1$s был разрублен приёмом «Восхождение» %2$s при помощи %3$s',
 'death.attack.scythe_combo': '%1$s был разрезан пополам, а затем ещё раз %2$s',
 'death.attack.scythe_combo.item': '%1$s был разрезан пополам, а затем ещё раз %2$s при помощи %3$s',
 'death.attack.scythe_maelstrom': '%1$s был изрублен в куски %2$s',
 'death.attack.scythe_maelstrom.item': '%1$s был изрублен в куски %2$s при помощи %3$s',
 'death.attack.scythe_melee': '%1$s был разрезан пополам %2$s',
 'death.attack.scythe_melee.item': '%1$s был разрезан пополам %2$s при помощи %3$s',
 'death.attack.scythe_rebound': '%1$s был сражён вернувшейся косой %2$s',
 'death.attack.scythe_rebound.item': '%1$s был сражён вернувшейся косой %2$s при помощи %3$s',
 'death.attack.scythe_sweep': '%1$s был разрезан пополам %2$s',
 'death.attack.scythe_sweep.item': '%1$s был разрезан пополам %2$s при помощи %3$s',
 'death.attack.sundering_anchor_magic_combo': 'душа %1$s была сражена мукой %2$s',
 'death.attack.sundering_anchor_magic_combo.item': 'душа %1$s была сражена мукой %2$s при помощи %3$s',
 'death.attack.sundering_anchor_physical_combo': '%1$s был повержен муками %2$s',
 'death.attack.sundering_anchor_physical_combo.item': '%1$s был повержен муками %2$s при помощи %3$s',
 'death.attack.tyrving': 'на душе %1$s остались шрамы от %2$s',
 'death.attack.tyrving.item': 'на душе %1$s остались шрамы от %2$s, wielding %3$s',
 'death.attack.void': '%1$s подвергся эрозии реальности',
 'death.attack.void.player': '%1$s подвергся эрозии реальности при попытке сбежать от %2$s',
 'death.attack.voodoo': 'душа %1$s была расколота %2$s',
 'death.attack.voodoo.item': 'душа %1$s была расколота %2$s при помощи %3$s',
 'death.attack.voodoo_playerless': 'душа %1$s была расколота',
 'death.attack.voodoo_playerless.player': 'душа %1$s была расколота при попытке сбежать от %2$s',
 'death.attack.warlock_spirit_impact': 'душа %1$s была расколота %2$s',
 'death.attack.warlock_spirit_impact.item': 'душа %1$s была расколота %2$s при помощи %3$s',
 # ---- эффекты ----
 'effect.malum.arcanaphage': 'Арканофаг',
 'effect.malum.ascension': 'Восхождение',
 'effect.malum.ascension.description': 'Смягчает падение и уменьшает гравитацию после успешного восхождения косой.',
 'effect.malum.avarice': 'Алчность',
 'effect.malum.burning_fervor': 'Пылающее рвение',
 'effect.malum.burning_fervor.description': 'Ваши инструменты укреплены сиянием, увеличивая скорость добычи и атаки.',
 'effect.malum.cancerous_growth': 'Опухолевый рост',
 'effect.malum.cancerous_growth.description': 'Неуправляемый рост придаёт вам сил, увеличивая максимальное здоровье.',
 'effect.malum.desperate_need': 'Отчаянная нужда',
 'effect.malum.echoing_arcana': 'Эхом отзывающаяся аркана',
 'effect.malum.echoing_arcana.description': 'Неконтролируемое усиление делает вас мудрее, увеличивая арканный резонанс.',
 'effect.malum.fiery_embrace': 'Огненные объятия',
 'effect.malum.fiery_embrace.description': 'Тёплые объятия пламени окутывают вашу душу, исцеляя обожжённые шрамы.',
 'effect.malum.flawed_aim': 'Неточный прицел',
 'effect.malum.flowing_grasp': 'Текучая хватка',
 'effect.malum.flowing_grasp.description': 'Вы тянетесь к новой силе, увеличивая радиус действия и расстояние подбора предметов.',
 'effect.malum.gleeful_target': 'Радостная мишень',
 'effect.malum.gluttony': 'Чревоугодие',
 'effect.malum.gluttony.description': 'Вы питаетесь уязвимыми, увеличивая мастерство магии ценой голода.',
 'effect.malum.good_tides': 'Благоприятные приливы',
 'effect.malum.good_tides.description': 'Пусть каждая рыба, встретившая мой взгляд, познает истинный смысл страха, ибо я — вестник смерти. Бичь подводных тварей, мой крючок точен и непоколебим, когда я забрасываю его в водную бездну. Человек, отвергнутый этой равнодушной землёй, находит утешение в море. Мой единственный друг — червь на крючке. Он извивается, корчится, силясь превозмочь смертную бессмысленность, что пропитала этот бесплодный мир. Я одинок. Я пуст. И всё же я рыбачу.',
 'effect.malum.grim_certainty': 'Мрачная уверенность',
 'effect.malum.grim_certainty.description': '«Тяжесть миров» колеблется, запечатлевая следующий удар как критический.',
 'effect.malum.hatred': 'Ненависть',
 'effect.malum.howling_gale': 'Воющий шквал',
 'effect.malum.howling_gale.description': 'Зефир толкает вас вперёд, увеличивая скорость передвижения.',
 'effect.malum.imminent_deliverance': 'Неминуемое избавление',
 'effect.malum.imminent_deliverance.description': '«Грань избавления» колеблется, запечатлевая свой следующий удар как критический.',
 'effect.malum.lifted': 'Поднятый',
 'effect.malum.oaken_might': 'Дубовая мощь',
 'effect.malum.oaken_might.description': 'Ваши кулаки и инструменты укреплены землёй, увеличивая силу.',
 'effect.malum.rejected': 'Отверженный',
 'effect.malum.sacred_nourishment': 'Священное питание',
 'effect.malum.shaken_faith': 'Поколебленная вера',
 'effect.malum.silenced': 'Безмолвие',
 'effect.malum.silenced.description': 'Вы лишены голоса, и ваши магические способности подавлены.',
 'effect.malum.sky_tether': 'Небесный поводок',
 'effect.malum.sky_tether.description': 'Небеса зовут вас, увеличивая высоту прыжка и уменьшая гравитацию.',
 'effect.malum.stone_ward': 'Каменная защита',
 'effect.malum.stone_ward.description': 'Земляной панцирь окружает ваше тело, работая как дополнительная броня.',
 'effect.malum.trial_of_faith': 'Испытание веры',
 'effect.malum.true_shot': 'Верный выстрел',
 'effect.malum.wicked_empowerment': 'Скверное усиление',
 'effect.malum.wicked_intent': 'Скверный умысел',
 'effect.malum.wicked_intent.description': 'Вы готовите мощную контратаку: следующая атака косой обрушит невозможный град порезов.',
 'effect.malum.wyrd_exhaustion': 'Истощение вирда',
 # ---- зачарования ----
 'enchantment.malum.animated': 'Одушевлённый',
 'enchantment.malum.animated.desc': 'Увеличивает скорость атаки.',
 'enchantment.malum.ascension': 'Восхождение',
 'enchantment.malum.ascension.desc': 'Позволяет косе подбрасывать игрока вверх, нанося урон ближайшим врагам при использовании.',
 'enchantment.malum.capacitor': 'Конденсатор',
 'enchantment.malum.capacitor.desc': 'Добавляет дополнительные заряды заклинаний для использования с посохом.',
 'enchantment.malum.haunted': 'Призрачный',
 'enchantment.malum.haunted.desc': 'Увеличивает магический урон оружия.',
 'enchantment.malum.rebound': 'Отскок',
 'enchantment.malum.rebound.desc': 'Позволяет бросать косу при использовании.',
 'enchantment.malum.replenishing': 'Пополнение',
 'enchantment.malum.replenishing.desc': 'Восстанавливает заряды заклинаний при нанесении урона посохом в ближнем бою.',
 'enchantment.malum.spirit_plunder': 'Добыча духов',
 'enchantment.malum.spirit_plunder.desc': 'Даёт дополнительных духов при раскалывании души.',
 'enchantment.malum.weavers_haste': 'Спешка ткача',
 'enchantment.malum.weavers_haste.desc': 'Ускоряет любые очаги заклинаний, созданные инструментом.',
 'enchantment.malum.weavers_propagation': 'Распространение ткача',
 'enchantment.malum.weavers_propagation.desc': 'Призывает дополнительные очаги заклинаний при разрушении блока инструментом.',
}
