# -*- coding: utf-8 -*-
# Malum, часть 3г: подсказки эффектов (curio, geas, ключевые слова, реплики).
P3D = {
 # ---- curios ----
 'malum.effect.curio.always_sprint': 'Бег доступен всегда',
 'malum.effect.curio.ascension_launch': 'Восхождение подбрасывает цели вверх',
 'malum.effect.curio.bigger_explosions': 'Усиливает взрывы',
 'malum.effect.curio.burning_damage': 'Жгучий урон',
 'malum.effect.curio.burning_resistance': 'Сопротивление урону при горении',
 'malum.effect.curio.crits': 'Критические удары',
 'malum.effect.curio.eat_rotten': 'Гнилая пища вкуснее',
 'malum.effect.curio.enchanted_explosions': 'Взрывы зачарованы: %s',
 'malum.effect.curio.enhanced_maneuvers': 'Улучшает отскок и восхождение',
 'malum.effect.curio.explosion_drops_collected': 'Автоматический сбор добычи после взрыва',
 'malum.effect.curio.extend_positive_effect': 'Продлевает положительные эффекты',
 'malum.effect.curio.friendly_enemies': 'Снижает агрессию врагов',
 'malum.effect.curio.full_health_fake_collection': 'Удары по целям с полным здоровьем вызывают эффекты сбора духов',
 'malum.effect.curio.growing_gluttony': 'Поедание гнилой пищи продлевает чревоугодие',
 'malum.effect.curio.hunger_drain': 'Постоянно истощает голод',
 'malum.effect.curio.longer_rebound_cooldown': 'Отскок получает больший откат',
 'malum.effect.curio.low_health_speed': 'Скорость при низком здоровье',
 'malum.effect.curio.lower_ascension_damage': 'Восхождение получает штраф к урону',
 'malum.effect.curio.no_sweep': 'Отключает размашистые удары косой',
 'malum.effect.curio.ore_prospecting': 'Сбор драгоценных минералов иногда дарует алчность',
 'malum.effect.curio.pacifist_recharge': 'Если коса применяется, откат удлиняется',
 'malum.effect.curio.rebound_maelstrom': 'Отскок создаёт ветряной водоворот',
 'malum.effect.curio.rotten_gluttony': 'Поедание гнилой пищи порождает чревоугодие',
 'malum.effect.curio.scythe_chain': 'Более смертоносные размашистые удары косой',
 'malum.effect.curio.scythe_counterattack': 'Мощная контратака косой при получении удара',
 'malum.effect.curio.scythe_execution': 'Косы используют раны',
 'malum.effect.curio.shorten_negative_effect': 'Сокращает отрицательные эффекты',
 'malum.effect.curio.silence': 'Лишает атакующих голоса',
 'malum.effect.curio.soul_ward_complete_absorption': 'Оберег души поглощает весь урон',
 'malum.effect.curio.soul_ward_escalating_integrity': 'Оберег души обретает целостность, когда близок к распаду',
 'malum.effect.curio.soul_ward_long_shatter_cooldown': 'Долгая перезарядка оберега души после распада',
 'malum.effect.curio.soul_ward_magic_resilience': 'Оберег души перенаправляет магию',
 'malum.effect.curio.spirits_add_health': 'Сбор духов даёт дополнительные сердца',
 'malum.effect.curio.spirits_extend_effect': 'Сбор духов продлевает действие зелий',
 'malum.effect.curio.spirits_gluttony': 'Сбор духов порождает чревоугодие',
 'malum.effect.curio.spirits_heal': 'Сбор духов восполняет здоровье',
 'malum.effect.curio.spirits_weave_mana': 'Сбор духов восстанавливает оберег души',
 'malum.effect.curio.spirits_weave_mana_irons_spellbooks': 'Сбор духов восстанавливает ману заклинаний [Iron’s Spellbooks]',
 'malum.effect.curio.spirits_weave_resonance': 'Сбор духов порождаer арканный резонанс',
 'malum.effect.curio.spirits_weave_resonance_irons_spellbooks': 'Сбор духов снижает откат заклинаний [Iron’s Spellbooks]',
 'malum.effect.curio.spirits_xp': 'Сбор духов даёт очки опыта',
 'malum.effect.curio.totem_effect': 'Дарует: %s',
 # ---- оружие ----
 'malum.effect.edge_of_deliverance_crit': 'Следующие удары бьют критически',
 'malum.effect.edge_of_deliverance_unpowered_attack': 'Некритические удары наносят сниженный урон',
 'malum.effect.erosive_silence': 'Урон эрозии лишает цели голоса',
 'malum.effect.erosive_spread': 'Заряжает залп эрозионных суббоеприпасов',
 'malum.effect.hex_bolts': 'Заряжает залп мнемонических клинков',
 'malum.effect.soul_based_damage': 'Наносит урон, разрывающий душу',
 'malum.effect.sundering_anchor_damage_split': 'Урон распределяется между несколькими ударами',
 'malum.effect.sundering_anchor_hatred': 'Каждый удар накладывает ненависть',
 'malum.effect.unwinding_chaos_burn': 'Урон от горения восстанавливает заряды',
 'malum.effect.unwinding_chaos_volley': 'Заряжает залп составной энергии',
 'malum.effect.weight_of_worlds_crit': 'Иногда бьёт с критической силой',
 'malum.effect.weight_of_worlds_kill': 'Убийства гарантируют критический удар',
 # ---- сумки ----
 'malum.effect.ravenous_pouch_collection': 'Вырывает предметы, уже лежащие в хранилище',
 'malum.effect.ravenous_pouch_drop': 'При опустошении сохраняет минимум',
 'malum.effect.soulwoven_pouch_collection': 'Собирает духи арканы',
 'malum.effect.soulwoven_pouch_storage': 'Перебирает магические предметы',
 # ---- служебные ----
 'malum.effect.negative': '-%s',
 'malum.effect.positive': '+%s',
 'malum.effect.keyword.arcane_resonance': 'Арканный резонанс: усиливает эффекты сбора духов',
 'malum.effect.keyword.avarice': 'Алчность: постепенно повышает удачу',
 'malum.effect.keyword.gluttony': 'Чревоугодие: повышает магический урон, но истощает голод',
 'malum.effect.keyword.soul_ward': 'Оберег души: поглощает урон, перезаряжается со временем',
 # ---- геас ----
 'malum.effect.geas.aggressive_enemies': 'Повышает агрессию врагов',
 'malum.effect.geas.avarice_combustion': 'Алчность обволакивает вас пламенем при получении удара',
 'malum.effect.geas.avarice_explosions': 'Алчность сильнее усиливает взрывы и даёт шанс удачи',
 'malum.effect.geas.avarice_healing': 'Обретение алчности восстанавливает здоровье',
 'malum.effect.geas.avarice_vulnerability': 'Алчность повышает получаемый урон от взрывов',
 'malum.effect.geas.bonus_reach': 'Избегание вреда увеличивает радиус действия',
 'malum.effect.geas.buffered_damage': 'Половина входящего урона буферизуется',
 'malum.effect.geas.buffered_damage_more_overall': 'Буферизованный урон усиливается',
 'malum.effect.geas.buffered_damage_non_lethal': 'Буферизованный урон наносится со временем и не может убить вас',
 'malum.effect.geas.chained_spirit_bonus': 'Повторные раскалывания душ приносят дополнительную аркану',
 'malum.effect.geas.conduit_bonus': 'Сила кондуита восстанавливает здоровье и усиливает перечисленные эффекты',
 'malum.effect.geas.damage_buildup': 'Получение урона заряжает ярость',
 'malum.effect.geas.damage_release': 'Ярость высвобождается при ударе по цели',
 'malum.effect.geas.desperate_need': 'Чревоугодие становится отчаянной нуждой',
 'malum.effect.geas.desperate_need_betrayal': 'Гниение поглотит вас',
 'malum.effect.geas.desperate_need_scythe_proficiency': 'Отчаянная нужда существенно повышает мастерство косы',
 'malum.effect.geas.explosion_lover': 'Взрывы даруют алчность',
 'malum.effect.geas.extinguish_hurt': 'Когда вас тушат, вы получаете урон',
 'malum.effect.geas.faster_draw_time': 'Успешный урон из лука накапливает скорость натяжения',
 'malum.effect.geas.faster_natural_healing': 'Насыщение исцеляет быстрее',
 'malum.effect.geas.faster_starving': 'Истощение наступает быстрее',
 'malum.effect.geas.first_hit_bonus': 'Разит здоровых врагов скверной энергией',
 'malum.effect.geas.fish_healing': 'Вы не можете исцеляться вне воды',
 'malum.effect.geas.food_effect_cleanse': 'Еда снимает отрицательные эффекты',
 'malum.effect.geas.fragile_reach': 'Эффект радиуса уходит в откат при получении удара',
 'malum.effect.geas.fragile_reach_slowdown': 'Состояние отката снижает скорость передвижения',
 'malum.effect.geas.gleeful_target': 'Недуги, благословения и проклятия замирают при получении удара',
 'malum.effect.geas.gleeful_target_arcane_resonance': 'Арканный резонанс продлевает стазис',
 'malum.effect.geas.healing_aura': 'Исцеление делится с ближайшими существами',
 'malum.effect.geas.healing_aura_no_filter': 'Общее исцеление лечит всех — и союзников, и врагов',
 'malum.effect.geas.high_hunger_more_armor': 'Сытая жизнь даёт дополнительную броню',
 'malum.effect.geas.hotter_fire': 'Наложенные вами эффекты горения ускоряются',
 'malum.effect.geas.hunger_as_withdrawal': 'Пристрастие к бойне',
 'malum.effect.geas.incoming_fall_damage_auto_attack': 'Урон от падения атакует ближайшие цели',
 'malum.effect.geas.inverted_heart': 'Раны, чувства и ощущения передаются свидетелям',
 'malum.effect.geas.inverted_heart_arcane_resonance': 'Арканный резонанс увеличивает радиус влияния',
 'malum.effect.geas.knockback_also_accelerates': 'Высокий импульс усиливает получаемое отбрасывание',
 'malum.effect.geas.low_hunger_less_armor': 'Истощение вдвое снижает броню',
 'malum.effect.geas.malignant_crit_aegis_rerouting': 'Злокачественное избавление перезаряжает злокачественную эгиду',
 'malum.effect.geas.malignant_crit_combo': 'Злокачественное избавление раз за разом полосует цели',
 'malum.effect.geas.malignant_crit_combo_reinforcement': 'Удары усиливаются за счёт злокачественного преобразования',
 'malum.effect.geas.malignant_crit_healing_overexertion': 'Частые срабатывания постепенно ослабляют всё исцеление',
 'malum.effect.geas.malignant_crit_leech': 'Злокачественное избавление вытягивает жизненную силу',
 'malum.effect.geas.malignant_crit_reduced_damage': 'Перезарядка снижает урон злокачественного избавления',
 'malum.effect.geas.missing_halts_draw_time': 'Промах обращает преимущество вспять',
 'malum.effect.geas.more_damage': 'Весь входящий урон удваивается',
 'malum.effect.geas.more_knockback': 'Удваивает входящее отбрасывание',
 'malum.effect.geas.more_runes': '2 слота рун',
 'malum.effect.geas.more_saturation': 'Трапеза даёт больше насыщения',
 'malum.effect.geas.movement_acceleration': 'Бег накапливает дополнительный импульс',
 'malum.effect.geas.no_armor': 'Надетая броня сковывает вас',
 'malum.effect.geas.no_armor_druid_armor': 'Отсутствие надетой брони даёт броню и усиливает исцеление',
 'malum.effect.geas.no_normal_foods': 'Вы можете есть только гниль',
 'malum.effect.geas.no_passive_healing': 'Насыщение и голод больше не восстанавливают здоровье',
 'malum.effect.geas.only_scythe': 'Обычное оружие рассыпается в ваших руках',
 'malum.effect.geas.oops_all_magic': 'Весь входящий урон становится магическим',
 'malum.effect.geas.ore_prospecting': 'Сбор драгоценных минералов дарует алчность',
 'malum.effect.geas.outgoing_fall_damage_auto_attack': 'Исходящий урон от падения атакует цели независимо от расстояния',
 'malum.effect.geas.passive_healing': 'Пассивно восстанавливает здоровье',
 'malum.effect.geas.poison_slash': 'Отчаянная нужда позволяет косе наносить ядовитые удары',
 'malum.effect.geas.poison_slash_consumes_desperate_need': 'Отчаянная нужда исчезает при атаке',
 'malum.effect.geas.presence_breaker': 'На цели накладываются отказ, отстранённость и изгнание',
 'malum.effect.geas.presence_breaker_arcane_resonance': 'Арканный резонанс увеличивает длительность изгнания',
 'malum.effect.geas.rocket_jumping': 'Порывы ветра усиливаются и даруют восхождение',
 'malum.effect.geas.rotten_healing': 'Поедание гнилой пищи исцеляет вас',
 'malum.effect.geas.rune_vulnerability': 'Каждая надетая руна ослабляет исцеление, броню и сопротивление магии',
 'malum.effect.geas.scythe_combo': 'Удары косы создают серии атак',
 'malum.effect.geas.soul_ward_on_hit': 'Магический урон восстанавливает оберег души',
 'malum.effect.geas.spirits_absorption': 'Сбор духов даёт поглощение',
 'malum.effect.geas.spirits_hunger': 'Сбор духов истощает голод',
 'malum.effect.geas.spirits_magic_boost': 'Сбор духов усиливает магию',
 'malum.effect.geas.staff_autofire': 'Заряды посоха выстреливают сами',
 'malum.effect.geas.staff_homing': 'Снаряды посоха наводятся на цели',
 'malum.effect.geas.trial_of_faith': 'Чревоугодие становится испытанием веры',
 'malum.effect.geas.trial_of_faith_healing': 'Испытание веры увеличивает получаемое исцеление',
 'malum.effect.geas.vastly_bigger_explosions': 'Значительно усиливает взрывы',
 'malum.effect.geas.water_agility': 'В воде вы двигаетесь и размахиваете быстрее',
 'malum.effect.geas.water_damage_resistance': 'В воде вы получаете сниженный урон',
 'malum.effect.geas.weak_legs': 'Урон от падения усиливается',
 'malum.effect.geas.wind_gliding': 'Эффект восхождения улучшает маневренность в воздухе',
 'malum.effect.geas.wyrd_reconstruction': 'Смерть вызывает возрождение',
 'malum.effect.geas.wyrd_reconstruction_cooldown': 'Арканный резонанс ослаблен до перезарядки',
 'malum.effect.geas.wyrd_reconstruction_spirits': 'Возрождение повторно вызывает эффекты сбора духов',
 # ---- реплики Wayne June ----
 'malum.effect.wayne_june.0': 'Железная корона. Загадочная и повсеместная.',
 'malum.effect.wayne_june.1': 'Полукруг, излучающий пять точек силы. Символ, скрытый глубоко в иконографии каждой древней империи.',
 'malum.effect.wayne_june.2': 'Точка невозврата приветствует вас с распростёртыми объятиями.',
 'malum.effect.wayne_june.3': 'Величайший ужас, кажется, — это вообще ничто.',
 'malum.effect.wayne_june.4': 'Океан пустоты, медленно поглощающий мир.',
 'malum.effect.wayne_june.5': 'Смутный кошмар, апокалипсис, которому можем противостоять только мы.',
 'malum.effect.wayne_june.6': 'Застойная и бескрайняя, эта адская бездна простирается за пределами самого рассудка.',
 'malum.effect.wayne_june.7': 'Мы странствуем по неисчислимым измерениям человеческой слабости.',
 'malum.effect.wayne_june.8': 'Успех, к которому так долго стремились, вознаграждается лишь подступающим откровением.',
 'malum.effect.wayne_june.9': 'Вы довольно долго корчились в своём трусливом отрицании.',
 'malum.effect.wayne_june.10': 'Позвольте нам вытащить ваши слежавшиеся унижения на свет.',
}
