# -*- coding: utf-8 -*-
# Malum, часть 4а: интерфейс — усиления, тигель, духи, ритуалы, риты.
P4A = {
 # ---- интерфейс мелочи ----
 'malum.gui.slot': 'Слот: ',
 'malum.gui.augment.installed': 'При установке: ',
 'malum.gui.augment.type.augment': 'Усиление',
 'malum.gui.augment.type.core_augment': 'Основное усиление',
 'malum.gui.ritual.tier': 'Уровень ритуала: ',
 'malum.gui.ritual.type': 'Тип ритуала: ',
 # ---- атрибуты тигля ----
 'malum.gui.crucible.attribute.caustic_synergy': 'Едкая синергия',
 'malum.gui.crucible.attribute.chain_focusing_chance': 'Шанс цепной фокусировки',
 'malum.gui.crucible.attribute.damage_absorption_chance': 'Шанс поглощения урона',
 'malum.gui.crucible.attribute.focusing_speed': 'Скорость фокусировки',
 'malum.gui.crucible.attribute.fortune_chance': 'Шанс удачи',
 'malum.gui.crucible.attribute.fuel_usage_rate': 'Расход топлива',
 'malum.gui.crucible.attribute.instability': 'Нестабильность',
 'malum.gui.crucible.attribute.misfortune_reversal': 'Обращение неудачи',
 'malum.gui.crucible.attribute.resonance_tuning': 'Резонансная настройка',
 'malum.gui.crucible.attribute.restoration_chance': 'Шанс восстановления',
 'malum.gui.crucible.attribute.tuning_potency': 'Сила настройки',
 'malum.gui.crucible.attribute.tuning_strain': 'Напряжение настройки',
 'malum.gui.crucible.attribute.weakness_tuning': 'Настройка слабости',
 # ---- духи: названия, счётчики и «вкусы» ----
 'malum.gui.spirit.aerial': 'Воздушный',
 'malum.gui.spirit.aerial.counted': '%1$s воздушных',
 'malum.gui.spirit.aerial.flavour': 'Стремительный',
 'malum.gui.spirit.aqueous': 'Водный',
 'malum.gui.spirit.aqueous.counted': '%1$s водных',
 'malum.gui.spirit.aqueous.flavour': 'Податливый',
 'malum.gui.spirit.arcane': 'Арканный',
 'malum.gui.spirit.arcane.counted': '%1$s арканных',
 'malum.gui.spirit.arcane.flavour': 'Фундаментальный',
 'malum.gui.spirit.earthen': 'Земляной',
 'malum.gui.spirit.earthen.counted': '%1$s земляных',
 'malum.gui.spirit.earthen.flavour': 'Устойчивый',
 'malum.gui.spirit.eldritch': 'Элдритческий',
 'malum.gui.spirit.eldritch.counted': '%1$s элдритческих',
 'malum.gui.spirit.eldritch.flavour': 'Эзотерический',
 'malum.gui.spirit.infernal': 'Инфернальный',
 'malum.gui.spirit.infernal.counted': '%1$s инфернальных',
 'malum.gui.spirit.infernal.flavour': 'Сияющий',
 'malum.gui.spirit.sacred': 'Сакральный',
 'malum.gui.spirit.sacred.counted': '%1$s сакральных',
 'malum.gui.spirit.sacred.flavour': 'Невинный',
 'malum.gui.spirit.umbral': 'Теневой',
 'malum.gui.spirit.umbral.counted': '%1$s теневых',
 'malum.gui.spirit.umbral.flavour': 'Антитезис',
 'malum.gui.spirit.wicked': 'Скверный',
 'malum.gui.spirit.wicked.counted': '%1$s скверных',
 'malum.gui.spirit.wicked.flavour': 'Злобный',
 # ---- риты ----
 'malum.gui.rite.rite_of_ascension': 'Ритуал восхождения',
 'malum.gui.rite.rite_of_ascension.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над блоками, он применяет эффект обратной гравитации, как у песка или гравия\nЭффект обратной гравитации поднимает блоки на высоту до шестнадцати блоков\nЭффект действует только на блоки, которые можно сохранить с помощью «Шёлкового касания»',
 'malum.gui.rite.rite_of_creation': 'Ритуал созидания',
 'malum.gui.rite.rite_of_creation.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над пустым пространством, он образует булыжник там, где это возможно',
 'malum.gui.rite.rite_of_culling': 'Ритуал выбраковки',
 'malum.gui.rite.rite_of_culling.effect': 'Затронутые животные уничтожаются\nЭффект требует перенаселения среди данного вида',
 'malum.gui.rite.rite_of_destruction': 'Ритуал разрушения',
 'malum.gui.rite.rite_of_destruction.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над блоками, он пытается их разрушить\nБлоки разрушаются независимо от требований к инструменту, если это в принципе возможно',
 'malum.gui.rite.rite_of_empowerment': 'Ритуал усиления',
 'malum.gui.rite.rite_of_empowerment.effect': 'Затронутые враждебные существа получают скверное усиление\nСкверное усиление увеличивает урон и запас здоровья',
 'malum.gui.rite.rite_of_gravity': 'Ритуал гравитации',
 'malum.gui.rite.rite_of_gravity.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над блоками, он применяет эффект гравитации, как у песка или гравия\nЭффект гравитации действует только на блоки, которые можно сохранить с помощью «Шёлкового касания»',
 'malum.gui.rite.rite_of_harming': 'Ритуал вреда',
 'malum.gui.rite.rite_of_harming.effect': 'Затронутые существа получают урон в два сердца',
 'malum.gui.rite.rite_of_healing': 'Ритуал исцеления',
 'malum.gui.rite.rite_of_healing.effect': 'Затронутые существа исцеляются на два сердца',
 'malum.gui.rite.rite_of_lust': 'Ритуал похоти',
 'malum.gui.rite.rite_of_lust.effect': 'Затронутые животные обретают силу\nЭффект прекращается, когда данный вид становится слишком многочисленным',
 'malum.gui.rite.rite_of_nourishment': 'Ритуал насыщения',
 'malum.gui.rite.rite_of_nourishment.effect': 'Затронутые игроки получают священное питание\nСвященное питание медленно поглощает истощение',
 'malum.gui.rite.rite_of_nurturing': 'Ритуал взращивания',
 'malum.gui.rite.rite_of_nurturing.effect': 'Затронутые животные взрослеют на двадцать пять секунд\nРазные виды реагируют по-разному:\n Овцы чаще едят траву\n Куры чаще несут яйца\n Пчёлы опыляют быстрее и чаще\n Аллаи размножаются быстрее',
 'malum.gui.rite.rite_of_quickening': 'Ритуал ускорения',
 'malum.gui.rite.rite_of_quickening.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над печами, он ускоряет процесс плавки\nРасход топлива остаётся пропорциональным',
 'malum.gui.rite.rite_of_rending': 'Ритуал растерзания',
 'malum.gui.rite.rite_of_rending.effect': 'Затронутые монстры получают смертельный удар',
 'malum.gui.rite.rite_of_sapping': 'Ритуал источения',
 'malum.gui.rite.rite_of_sapping.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над котлами, он ускоряет накопление жидкости из любого заострённого капельника сверху',
 'malum.gui.rite.rite_of_smelting': 'Ритуал плавки',
 'malum.gui.rite.rite_of_smelting.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над блоками, он пытается их переплавить\nБлоки переплавляются так, словно находятся в печи',
 'malum.gui.rite.rite_of_soaking': 'Ритуал орошения',
 'malum.gui.rite.rite_of_soaking.effect': 'Создаёт связанный очаг ритуала\nКогда очаг проходит над растениями, он применяет эффект, ускоряющий рост\nПосевы получают мгновенный эффект ускорения времени\nПрочие растения, на которые действует костная мука, растут, словно от настоящей костной муки\nПроходя над вспаханной землёй, очаг воздействует на посев сверху',
 'malum.gui.rite.rite_of_the_burning_fervor': 'Ритуал пылающего рвения',
 'malum.gui.rite.rite_of_the_burning_fervor.effect': 'Затронутые существа получают благословение «Пылающее рвение»\nПылающее рвение повышает скорость атаки и скорость добычи на две пятых',
 'malum.gui.rite.rite_of_the_fiery_embrace': 'Ритуал огненных объятий',
 'malum.gui.rite.rite_of_the_fiery_embrace.effect': 'Затронутые существа перестают гореть и получают благословение «Огненные объятия»\nОгненные объятия восстанавливают одно сердце дважды в секунду\nДействует только на горящих существ',
 'malum.gui.rite.rite_of_the_flowing_grasp': 'Ритуал текучей хватки',
 'malum.gui.rite.rite_of_the_flowing_grasp.effect': 'Затронутые существа получают благословение «Текучая хватка»\nТекучая хватка увеличивает радиус взаимодействия с блоками и расстояние подбора предметов на две пятых',
 'malum.gui.rite.rite_of_the_good_tides': 'Ритуал благоприятных приливов',
 'malum.gui.rite.rite_of_the_good_tides.effect': 'Затронутые существа получают благословение «Благоприятные приливы»\nБлагоприятные приливы дают эффекты, равные одному уровню зачарований «Приманка» и «Морская удача»',
 'malum.gui.rite.rite_of_the_howling_gale': 'Ритуал воющего шквала',
 'malum.gui.rite.rite_of_the_howling_gale.effect': 'Затронутые существа получают благословение «Воющий шквал»\nВоющий шквал повышает скорость передвижения и скорость атаки на две пятых.',
 'malum.gui.rite.rite_of_the_oaken_might': 'Ритуал дубовой мощи',
 'malum.gui.rite.rite_of_the_oaken_might.effect': 'Затронутые существа получают благословение «Дубовая мощь»\nДубовая мощь увеличивает наносимый урон на одно сердце\nС пустыми руками мощь удваивается',
 'malum.gui.rite.rite_of_the_sky_tether': 'Ритуал небесного поводка',
 'malum.gui.rite.rite_of_the_sky_tether.effect': 'Затронутые существа получают благословение «Небесный поводок»\nНебесный поводок уменьшает гравитацию и увеличивает высоту прыжка — каждое на две пятых\nУрон от падения также умеренно снижен',
 'malum.gui.rite.rite_of_the_stone_ward': 'Ритуал каменной защиты',
 'malum.gui.rite.rite_of_the_stone_ward.effect': 'Затронутые существа получают благословение «Каменная защита»\nКаменная защита снижает получаемый урон на одну пятую\nБез надетой брони защита удваивается',
 'malum.gui.rite.unchained_rite': 'Освобождённый ритуал',
 'malum.gui.rite.unchained_rite.effect': 'Создаёт связанный очаг ритуала\nОчаг движется сквозь порчу и воздействует на блок сверху\nЗатронутые блоки подвергаются освобождённой трансмутации\nЧтобы существовать, очагу нужна порча',
 'malum.gui.rite.undirected_rite': 'Ненаправленный ритуал',
 'malum.gui.rite.undirected_rite.effect': 'Примечание: требуется сдерживание',
 # ---- метки ритов ----
 'malum.gui.rite.tag.aura': 'Аура',
 'malum.gui.rite.tag.greater': 'Великий рит',
 'malum.gui.rite.tag.lesser': 'Малый рит',
 'malum.gui.rite.tag.locus_effect': 'Эффект связанного очага',
 'malum.gui.rite.tag.radial_effect': 'Эффект по площади',
 'malum.gui.rite.tag.runewood': 'Рунное дерево',
 'malum.gui.rite.tag.soulwood': 'Дерево душ',
 'malum.gui.rite.tag.strange_effect': 'Странный эффект',
}
